#****************************************************************************
# Copyright 2019-2026 Matthew Ballance and contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#****************************************************************************
"""
zuspec.synth: Synthesis transformations for Zuspec IR.

This package provides:
- SPRTL (Synchronous Process RTL) transformations
- FSM generation from async processes
- Scheduling algorithms (ASAP, ALAP, list-based)
- Code generation backends
"""

from . import sprtl


def synthesize(cls, *, output=None, top=None, reset_style="sync_low",
               sdc_output=None, forward=True) -> str:
    """Synthesize a Zuspec component class to SystemVerilog.

    Detects whether *cls* is a pipeline component (annotated with
    ``@zdc.pipeline``) or a sequential/combinational component and routes
    to the appropriate internal pass chain.

    Parameters
    ----------
    cls:
        Component class decorated with ``@zdc.dataclass``.
    output:
        File path to write the ``.sv`` file.  If omitted the SV text is
        returned but not written.
    top:
        Override the generated module name (default: ``cls.__name__``).
    reset_style:
        ``"sync_low"`` (default), ``"sync_high"``, ``"async_low"``,
        ``"async_high"``.  Ignored when the component declares an explicit
        ``ResetDomain`` (the domain's ``style`` and ``polarity`` take
        precedence).
    sdc_output:
        File path to write a Synopsys Design Constraints (``.sdc``) file.
        Only generated when the component declares a ``ClockDomain`` with a
        known ``period``.
    forward:
        Enable RAW hazard forwarding for pipeline components.  Ignored for
        non-pipeline components.

    Returns
    -------
    str
        Generated SystemVerilog source code.
    """
    is_pipeline = _detect_pipeline(cls)
    if is_pipeline:
        sv = _synthesize_pipeline(cls, forward=forward, top=top)
    else:
        sv = _synthesize_sprtl(cls, reset_style=reset_style, top=top)

    if output is not None and sv:
        with open(output, "w") as fh:
            fh.write(sv)

    if sdc_output is not None:
        sdc = _generate_sdc(cls, top=top)
        if sdc:
            with open(sdc_output, "w") as fh:
                fh.write(sdc)

    return sv


def _generate_sdc(cls, top=None) -> str:
    """Generate a minimal SDC file from a component's ClockDomain declarations.

    Returns an empty string if the component has no ``ClockDomain`` with a
    known ``period``.

    When the component is (or contains) a :class:`~zuspec.dataclasses.cdc.TwoFFSync`,
    a ``set_false_path`` constraint is also emitted for the first synchroniser
    stage register.
    """
    from zuspec.dataclasses.data_model_factory import DataModelFactory
    from zuspec.ir.core.data_type import DataTypeComponent
    from zuspec.synth.sprtl.fsm_ir import DomainBinding

    ctx = DataModelFactory().build(cls)
    type_name = getattr(cls, "__qualname__", None) or cls.__name__
    component_ir = ctx.type_m.get(type_name) or ctx.type_m.get(cls.__name__)
    if component_ir is None:
        return ""

    db = DomainBinding.from_component_ir(component_ir)
    module_name = top or cls.__name__

    lines = [f"# Generated by zuspec-synth for {module_name}"]

    # create_clock only when period is known
    if db.period is not None:
        try:
            period_ns = db.period.as_ns()
        except Exception:
            period_ns = float(str(db.period))
        lines.append(
            f"create_clock -name {db.clock_name} -period {period_ns}"
            f" [get_ports {db.clock_name}]"
        )

    # ------------------------------------------------------------------ #
    # TwoFFSync set_false_path generation                                  #
    # ------------------------------------------------------------------ #
    # Case 1: the class itself IS a TwoFFSync primitive.
    if getattr(cls, "_zdc_two_ff_sync", False):
        src_clk = getattr(cls, "src_domain", None) or "*"
        lines.append(
            f"set_false_path -from [get_clocks {{{src_clk}}}]"
            f" -to [get_cells {{*_sync0_reg}}]"
        )
    else:
        # Case 2: look for TwoFFSync sub-instances in the hierarchy.
        import dataclasses as _dc
        py_fields_meta: dict = {}
        if hasattr(cls, "__dataclass_fields__"):
            for pf in _dc.fields(cls):
                py_fields_meta[pf.name] = (pf.metadata, pf.type)

        for f in component_ir.fields:
            if type(f).__name__ != "Field":
                continue
            _, py_type = py_fields_meta.get(f.name, ({}, None))
            py_cls = py_type if isinstance(py_type, type) else None
            if py_cls and getattr(py_cls, "_zdc_two_ff_sync", False):
                src_clk = getattr(py_cls, "src_domain", None) or "*"
                lines.append(
                    f"set_false_path -from [get_clocks {{{src_clk}}}]"
                    f" -to [get_cells {{*{f.name}/_sync0_reg}}]"
                )

    result = "\n".join(lines) + "\n"
    # If the only line is the header comment, return empty (nothing useful).
    if len(lines) == 1:
        return ""
    return result

# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _detect_pipeline(cls) -> bool:
    """Return True if *cls* has a method decorated with ``@zdc.pipeline``."""
    for name in dir(cls):
        try:
            member = getattr(cls, name)
        except AttributeError:
            continue
        if callable(member) and hasattr(member, "_zdc_pipeline"):
            return True
    return False


def _reset_style_enum(reset_style: str):
    from zuspec.synth.sprtl import ResetStyle
    _map = {
        "sync_low":   ResetStyle.SYNC_LOW,
        "sync_high":  ResetStyle.SYNC_HIGH,
        "async_low":  ResetStyle.ASYNC_LOW,
        "async_high": ResetStyle.ASYNC_HIGH,
    }
    return _map.get(reset_style.lower(), ResetStyle.SYNC_LOW)


def _synthesize_pipeline(cls, *, forward: bool = True, top=None) -> str:
    """Run the pipeline pass chain and return SV text."""
    from zuspec.dataclasses.data_model_factory import DataModelFactory
    from zuspec.synth.ir.synth_ir import SynthIR, SynthConfig
    from zuspec.synth.passes import (
        PipelineFrontendPass,
        AutoThreadPass,
        HazardAnalysisPass,
        ForwardingGenPass,
        StallGenPass,
        SyncBodyLowerPass,
        SVEmitPass,
    )

    cfg = SynthConfig(forward_default=True if forward else False)

    ir = SynthIR()
    ir.component = cls
    ir.model_context = DataModelFactory().build(cls)

    for pass_cls in [
        PipelineFrontendPass,
        AutoThreadPass,
        HazardAnalysisPass,
        ForwardingGenPass,
        StallGenPass,
        SyncBodyLowerPass,
    ]:
        ir = pass_cls(cfg).run(ir)

    ir = SVEmitPass(cfg).run(ir)
    sv = ir.lowered_sv.get("sv/pipeline/top", "")

    if top and sv:
        # Replace the first occurrence of the default module name
        sv = sv.replace(f"module {cls.__name__}", f"module {top}", 1)

    return sv


def _synthesize_sprtl(cls, *, reset_style: str = "sync_low", top=None) -> str:
    """Run the SPRTL transformer + SV codegen and return SV text.

    Handles both sync/comb mixed components (via FSM) and pure-comb
    components (via a simple always_comb module skeleton).
    Handles hierarchical components (sub-instances) via _synthesize_hierarchical.
    """
    from zuspec.dataclasses.data_model_factory import DataModelFactory
    from zuspec.synth.sprtl import (
        SPRTLTransformer,
        generate_sv,
        SVGenConfig,
    )

    ctx = DataModelFactory().build(cls)
    module_name = top or cls.__name__

    # DataModelFactory keys type_m by __qualname__ when available
    component_ir = ctx.type_m.get(getattr(cls, "__qualname__", None)) \
                   or ctx.type_m.get(cls.__name__)

    if component_ir is None:
        raise ValueError(
            f"synthesize: could not find IR for {cls.__name__!r}.  "
            f"Available keys: {list(ctx.type_m.keys())}"
        )

    # Hierarchical components (with sub-instances) get their own path.
    if _is_hierarchical(component_ir, ctx):
        return _synthesize_hierarchical(cls, component_ir, ctx, module_name)

    sync_processes = getattr(component_ir, "sync_processes", [])
    proc_processes = getattr(component_ir, "proc_processes", [])

    if sync_processes:
        proc = sync_processes[0]
        if getattr(proc, "is_async", False):
            # Async (while True / await) path — use the SPRTL FSM transformer.
            reset_cfg = SVGenConfig(reset_style=_reset_style_enum(reset_style))
            transformer = SPRTLTransformer()
            fsm = transformer.transform(component_ir, proc)
            fsm.name = module_name
            sv = generate_sv(fsm, config=reset_cfg)
        else:
            # Plain-def one-cycle sync path — emit always_ff directly from IR.
            sv = _synthesize_simple_sync(
                component_ir, proc, module_name, reset_style,
                ctx=ctx, py_cls=cls,
            )
    elif proc_processes:
        # @zdc.proc Process nodes (e.g. Counter pattern)
        reg_proc_nodes = [p for p in proc_processes if type(p).__name__ == 'Process']
        if reg_proc_nodes:
            sv = _synthesize_reg_process(component_ir, reg_proc_nodes[0], module_name)
        else:
            sv = _build_comb_module(component_ir, module_name)
    else:
        # Pure-comb path: build a simple always_comb module skeleton.
        sv = _build_comb_module(component_ir, module_name)

    return sv


# ---------------------------------------------------------------------------
# Plain-def sync: direct IR → always_ff emitter
# ---------------------------------------------------------------------------

_BINOP_SV = {
    "Add": "+", "Sub": "-", "Mult": "*", "Div": "/", "Mod": "%",
    "BitAnd": "&", "BitOr": "|", "BitXor": "^",
    "LShift": "<<", "RShift": ">>",
    "And": "&&", "Or": "||",
    "Eq": "==", "NotEq": "!=",
    "Lt": "<", "LtE": "<=", "Gt": ">", "GtE": ">=",
}
_UNOP_SV = {"Not": "!", "USub": "-", "Invert": "~"}


def _ir_expr_to_sv(expr, idx_to_name: dict) -> str:
    """Recursively convert a DC IR expression to a SV string."""
    t = type(expr).__name__
    if t == "ExprRefField":
        return idx_to_name.get(expr.index, f"_f{expr.index}")
    if t == "ExprAttribute":
        base = _ir_expr_to_sv(expr.value, idx_to_name)
        return f"{base}_{expr.attr}"
    if t == "ExprConstant":
        return str(expr.value)
    if t == "ExprCall":
        # Reg.read() call: ExprCall(ExprAttribute(ExprRefField[i], 'read'), [])
        func = expr.func
        if func is not None and type(func).__name__ == "ExprAttribute":
            if func.attr == "read":
                base = func.value
                if base is not None and type(base).__name__ == "ExprRefField":
                    return idx_to_name.get(base.index, f"_f{base.index}")
        # General call — emit as function call (fallback)
        if func is not None:
            fn_str = _ir_expr_to_sv(func, idx_to_name)
            args_str = ", ".join(_ir_expr_to_sv(a, idx_to_name) for a in getattr(expr, 'args', []))
            return f"{fn_str}({args_str})"
    if t == "ExprBin":
        lhs = _ir_expr_to_sv(expr.lhs, idx_to_name)
        rhs = _ir_expr_to_sv(expr.rhs, idx_to_name)
        op_name = expr.op.name if hasattr(expr.op, "name") else str(expr.op)
        sv_op = _BINOP_SV.get(op_name, op_name)
        return f"({lhs} {sv_op} {rhs})"
    if t == "ExprUnary":
        operand = _ir_expr_to_sv(expr.operand, idx_to_name)
        op_name = expr.op.name if hasattr(expr.op, "name") else str(expr.op)
        sv_op = _UNOP_SV.get(op_name, op_name)
        return f"({sv_op}{operand})"
    if t == "ExprCompare":
        parts = [_ir_expr_to_sv(expr.left, idx_to_name)]
        for op, comparator in zip(expr.ops, expr.comparators):
            op_name = op.name if hasattr(op, "name") else str(op)
            sv_op = _BINOP_SV.get(op_name, op_name)
            parts.append(sv_op)
            parts.append(_ir_expr_to_sv(comparator, idx_to_name))
        return "(" + " ".join(parts) + ")"
    # Fallbacks for simple wrapper objects
    if hasattr(expr, "name"):
        return expr.name
    if hasattr(expr, "value"):
        return str(expr.value)
    return str(expr)


def _ir_if_to_sv(stmt, idx_to_name: dict, indent: int, lines: list):
    """Emit an if/elif/else chain from a StmtIf IR node."""
    sp = " " * indent
    cond = _ir_expr_to_sv(stmt.test, idx_to_name)
    lines.append(f"{sp}if ({cond}) begin")
    lines.extend(_ir_stmts_to_sv(stmt.body, idx_to_name, indent + 2))

    orelse = stmt.orelse
    while orelse:
        if len(orelse) == 1 and type(orelse[0]).__name__ == "StmtIf":
            inner = orelse[0]
            inner_cond = _ir_expr_to_sv(inner.test, idx_to_name)
            lines.append(f"{sp}end else if ({inner_cond}) begin")
            lines.extend(_ir_stmts_to_sv(inner.body, idx_to_name, indent + 2))
            orelse = inner.orelse
        else:
            lines.append(f"{sp}end else begin")
            lines.extend(_ir_stmts_to_sv(orelse, idx_to_name, indent + 2))
            orelse = []

    lines.append(f"{sp}end")


def _field_bits(f) -> int:
    """Return the bit width for a field, defaulting to 32 for unbounded int."""
    bits = getattr(getattr(f, "datatype", None), "bits", 1)
    if bits is None or bits < 1:
        return 32  # unbounded Python int → 32-bit SV logic
    return bits


def _width_str(bits: int) -> str:
    return f"[{bits - 1}:0] " if bits > 1 else "       "


def _ir_stmts_to_sv_comb(stmts, idx_to_name: dict, indent: int = 2) -> list:
    """Convert IR statements to SV lines using blocking (=) assignments for always_comb."""
    lines = []
    sp = " " * indent
    for stmt in stmts:
        t = type(stmt).__name__
        if t == "StmtAssign":
            for target in stmt.targets:
                tgt = _ir_expr_to_sv(target, idx_to_name)
                val = _ir_expr_to_sv(stmt.value, idx_to_name)
                lines.append(f"{sp}{tgt} = {val};")
        elif t == "StmtAugAssign":
            tgt = _ir_expr_to_sv(stmt.target, idx_to_name)
            val = _ir_expr_to_sv(stmt.value, idx_to_name)
            op_name = stmt.op.name if hasattr(stmt.op, "name") else str(stmt.op)
            sv_op = _BINOP_SV.get(op_name, op_name)
            lines.append(f"{sp}{tgt} = {tgt} {sv_op} {val};")
        elif t == "StmtIf":
            _ir_if_to_sv_comb(stmt, idx_to_name, indent, lines)
    return lines


def _ir_if_to_sv_comb(stmt, idx_to_name: dict, indent: int, lines: list):
    """Emit an if/elif/else chain with blocking assignments for always_comb."""
    sp = " " * indent
    cond = _ir_expr_to_sv(stmt.test, idx_to_name)
    lines.append(f"{sp}if ({cond}) begin")
    lines.extend(_ir_stmts_to_sv_comb(stmt.body, idx_to_name, indent + 2))

    orelse = stmt.orelse
    while orelse:
        if len(orelse) == 1 and type(orelse[0]).__name__ == "StmtIf":
            inner = orelse[0]
            inner_cond = _ir_expr_to_sv(inner.test, idx_to_name)
            lines.append(f"{sp}end else if ({inner_cond}) begin")
            lines.extend(_ir_stmts_to_sv_comb(inner.body, idx_to_name, indent + 2))
            orelse = inner.orelse
        else:
            lines.append(f"{sp}end else begin")
            lines.extend(_ir_stmts_to_sv_comb(orelse, idx_to_name, indent + 2))
            orelse = []

    lines.append(f"{sp}end")


def _ir_stmts_to_sv(stmts, idx_to_name: dict, indent: int = 2) -> list:
    """Convert a list of IR statements to SV lines."""
    lines = []
    sp = " " * indent
    for stmt in stmts:
        t = type(stmt).__name__
        if t == "StmtAssign":
            for target in stmt.targets:
                tgt = _ir_expr_to_sv(target, idx_to_name)
                val = _ir_expr_to_sv(stmt.value, idx_to_name)
                lines.append(f"{sp}{tgt} <= {val};")
        elif t == "StmtAugAssign":
            tgt = _ir_expr_to_sv(stmt.target, idx_to_name)
            val = _ir_expr_to_sv(stmt.value, idx_to_name)
            op_name = stmt.op.name if hasattr(stmt.op, "name") else str(stmt.op)
            sv_op = _BINOP_SV.get(op_name, op_name)
            lines.append(f"{sp}{tgt} <= {tgt} {sv_op} {val};")
        elif t == "StmtIf":
            _ir_if_to_sv(stmt, idx_to_name, indent, lines)
        elif t == "StmtExpr":
            # Handle bare expression statements, including await reg.write(val)
            expr = stmt.expr
            if expr is not None and type(expr).__name__ == "ExprAwait":
                inner = expr.value
                if inner is not None and type(inner).__name__ == "ExprCall":
                    func = inner.func
                    if func is not None and type(func).__name__ == "ExprAttribute" and func.attr == "write":
                        base = func.value
                        if base is not None and type(base).__name__ == "ExprRefField":
                            field_name = idx_to_name.get(base.index, f"_f{base.index}")
                            args = getattr(inner, 'args', [])
                            val_sv = _ir_expr_to_sv(args[0], idx_to_name) if args else "'0"
                            lines.append(f"{sp}{field_name} <= {val_sv};")
                            continue
        elif t == "StmtWhile":
            # For the simple @proc pattern (while True: await reg.write(...))
            # just descend into the body — the always block wrapper handles the loop
            lines.extend(_ir_stmts_to_sv(stmt.body, idx_to_name, indent))
    return lines


def _synthesize_simple_sync(
    component_ir, process_ir, module_name: str, reset_style: str,
    ctx=None, py_cls=None,
) -> str:
    """Emit a plain always_ff module for a non-async one-cycle sync process."""
    import dataclasses as _dc
    fields = list(component_ir.fields)
    idx_to_name = {i: f.name for i, f in enumerate(fields)}

    # Python class field metadata (for bundle/mirror detection)
    py_fields_meta = {}
    if py_cls and hasattr(py_cls, "__dataclass_fields__"):
        for pf in _dc.fields(py_cls):
            py_fields_meta[pf.name] = pf.metadata

    metadata = getattr(process_ir, "metadata", {}) or {}
    clock_expr = metadata.get("clock")
    reset_expr = metadata.get("reset")

    # Prefer domain-based clock/reset if the component IR carries domain info
    from zuspec.synth.sprtl.fsm_ir import DomainBinding
    domain_binding = DomainBinding.from_component_ir(component_ir)
    if getattr(component_ir, "clock_domain", None) is not None:
        clock_name = domain_binding.clock_name
    else:
        clock_name = (
            idx_to_name.get(getattr(clock_expr, "index", -1), "clk")
            if clock_expr is not None
            else "clk"
        )
    if getattr(component_ir, "reset_domain", None) is not None:
        reset_name = domain_binding.reset_name
        reset_active_low = domain_binding.reset_active_low
        reset_async = domain_binding.reset_async
    else:
        reset_name = (
            idx_to_name.get(getattr(reset_expr, "index", -1), "rst_n")
            if reset_expr is not None
            else "rst_n"
        )
        reset_active_low = bool(metadata.get("reset_active_low", True))
        reset_async = bool(metadata.get("reset_async", False))

    # Build port list and internal signals
    ports = []
    internals = []
    # When clock_domain is set and no explicit clock field exists, inject clock port
    has_clock_field = any(getattr(f, "name", "") == clock_name for f in fields)
    if getattr(component_ir, "clock_domain", None) is not None and not has_clock_field:
        ports.append(f"  input  logic        {clock_name}")
    for f in fields:
        is_out = getattr(f, "is_out", None)
        bits = _field_bits(f)
        width_str = _width_str(bits)

        # Check for bundle/mirror struct field
        dt = getattr(f, "datatype", None)
        if ctx and dt and type(dt).__name__ == "DataTypeRef":
            struct_ir = ctx.type_m.get(dt.ref_name)
            if struct_ir and type(struct_ir).__name__ == "DataTypeStruct":
                is_mirror = py_fields_meta.get(f.name, {}).get("kind") == "mirror"
                for sf in struct_ir.fields:
                    sf_is_out = getattr(sf, "is_out", True)
                    if is_mirror:
                        sf_is_out = not sf_is_out
                    sf_bits = _field_bits(sf)
                    sf_width = _width_str(sf_bits)
                    dir_kw = "output" if sf_is_out else "input "
                    ports.append(f"  {dir_kw} logic {sf_width}{f.name}_{sf.name}")
                continue  # bundle handled; skip normal port/internal logic

        if is_out is None:
            internals.append(f"  logic {width_str}{f.name};")
        else:
            dir_kw = "output" if is_out else "input "
            ports.append(f"  {dir_kw} logic {width_str}{f.name}")

    # Sensitivity list
    if reset_async:
        edge = "negedge" if reset_active_low else "posedge"
        sens = f"posedge {clock_name} or {edge} {reset_name}"
    else:
        sens = f"posedge {clock_name}"

    # Emit
    lines = [
        f"// Generated by zuspec-synth",
        f"`timescale 1ns/1ps",
        f"module {module_name} (",
        ",\n".join(ports),
        ");",
        "",
    ]
    if internals:
        lines.extend(internals)
        lines.append("")
    lines.append(f"always_ff @({sens}) begin")
    # When reset_domain is declared and fields carry reset_value, auto-generate
    # the synchronous/asynchronous reset clause — no manual 'if self.reset:' needed.
    reset_clauses = []
    if getattr(component_ir, "reset_domain", None) is not None:
        for f in fields:
            rv = getattr(f, "reset_value", None)
            if rv is not None:
                reset_clauses.append((f.name, int(rv)))
    if reset_clauses:
        cond = f"!{reset_name}" if reset_active_low else reset_name
        lines.append(f"  if ({cond}) begin")
        for fname, rval in reset_clauses:
            lines.append(f"    {fname} <= {rval};")
        lines.append(f"  end else begin")
        lines.extend(_ir_stmts_to_sv(getattr(process_ir, "body", []), idx_to_name, 4))
        lines.append(f"  end")
    else:
        lines.extend(_ir_stmts_to_sv(getattr(process_ir, "body", []), idx_to_name, 2))
    lines += ["end"]

    # Emit comb processes as always_comb blocks
    comb_processes = getattr(component_ir, "comb_processes", [])
    for comb_proc in comb_processes:
        lines.append("")
        lines.append("always_comb begin")
        lines.extend(_ir_stmts_to_sv_comb(getattr(comb_proc, "body", []), idx_to_name, 2))
        lines.append("end")

    lines += ["", "endmodule"]

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Hierarchical synthesis helpers
# ---------------------------------------------------------------------------

def _is_hierarchical(component_ir, ctx) -> bool:
    """Return True if the component has sub-component instance fields."""
    for f in component_ir.fields:
        if type(f).__name__ == "Field":
            dt = getattr(f, "datatype", None)
            if dt and type(dt).__name__ == "DataTypeRef":
                ref_ir = ctx.type_m.get(dt.ref_name)
                if ref_ir and type(ref_ir).__name__ == "DataTypeComponent":
                    return True
    return False


def _decode_bind_ref_h(expr, top_fields, ctx):
    """Decode one side of a bind_map entry.

    Returns ``(inst_name, port_name, field_ir, is_bundle, struct_ir)``:
    - ``inst_name``: sub-instance field name, or ``None`` for a top-level ref.
    - ``port_name``: port/field name within the inst (or top-level name).
    - ``field_ir``: the IR field object.
    - ``is_bundle``: True when the field type is a struct (bundle/mirror).
    - ``struct_ir``: the struct IR if is_bundle, else None.
    """
    t = type(expr).__name__
    if t != "ExprRefField":
        return (None, "?", None, False, None)

    base_t = type(expr.base).__name__
    if base_t == "TypeExprRefSelf":
        # Direct top-level field reference.
        f = top_fields[expr.index]
        return (None, f.name, f, False, None)

    if base_t == "ExprRefField":
        # Sub-instance field reference: expr.base is the inst field.
        inst_f = top_fields[expr.base.index]
        inst_name = inst_f.name
        dt = getattr(inst_f, "datatype", None)
        if dt and type(dt).__name__ == "DataTypeRef":
            sub_ir = ctx.type_m.get(dt.ref_name)
            if sub_ir:
                sub_fields = list(sub_ir.fields)
                sf = sub_fields[expr.index]
                sf_dt = getattr(sf, "datatype", None)
                is_bundle = False
                struct_ir = None
                if sf_dt and type(sf_dt).__name__ == "DataTypeRef":
                    cand = ctx.type_m.get(sf_dt.ref_name)
                    if cand and type(cand).__name__ == "DataTypeStruct":
                        is_bundle = True
                        struct_ir = cand
                return (inst_name, sf.name, sf, is_bundle, struct_ir)

    return (None, "?", None, False, None)


def _synthesize_hierarchical(cls, component_ir, ctx, module_name: str) -> str:
    """Generate a hierarchical wrapper module for a component with sub-instances."""
    import dataclasses as _dc

    top_fields = list(component_ir.fields)

    # Python class metadata: bundle/mirror/instance kind per field.
    py_fields_meta = {}
    if hasattr(cls, "__dataclass_fields__"):
        for pf in _dc.fields(cls):
            py_fields_meta[pf.name] = (pf.metadata, pf.type)

    # ------------------------------------------------------------------ #
    # 1. Classify top-level fields                                         #
    # ------------------------------------------------------------------ #
    top_scalar_ports = []  # (name, bits, is_out)
    sub_insts = []         # (field_name, type_name, sub_ir, sub_py_cls)

    for f in top_fields:
        ft = type(f).__name__
        if ft == "FieldInOut":
            bits = _field_bits(f)
            is_out = getattr(f, "is_out", False)
            top_scalar_ports.append((f.name, bits, is_out))
        elif ft == "Field":
            dt = getattr(f, "datatype", None)
            if dt and type(dt).__name__ == "DataTypeRef":
                ref_ir = ctx.type_m.get(dt.ref_name)
                if ref_ir and type(ref_ir).__name__ == "DataTypeComponent":
                    meta, py_type = py_fields_meta.get(f.name, ({}, None))
                    sub_py_cls = py_type if isinstance(py_type, type) else None
                    sub_insts.append((f.name, dt.ref_name, ref_ir, sub_py_cls))

    # ------------------------------------------------------------------ #
    # 2. Parse bind_map                                                    #
    # ------------------------------------------------------------------ #
    bound_ports = set()          # (inst_name, expanded_port_name)
    inst_port_to_top = {}        # (inst_name, port_name) → top_port_name
    internal_wires = {}          # wire_name → bits
    # bundle_wire_groups: info for connecting bundle-to-bundle binds
    # list of (wire_base, struct_ir, lhs_inst, lhs_port, rhs_inst, rhs_port)
    bundle_wire_groups = []

    for bind in component_ir.bind_map:
        lhs_info = _decode_bind_ref_h(bind.lhs, top_fields, ctx)
        rhs_info = _decode_bind_ref_h(bind.rhs, top_fields, ctx)
        lhs_inst, lhs_port, _lf, lhs_is_bundle, lhs_struct = lhs_info
        rhs_inst, rhs_port, _rf, rhs_is_bundle, rhs_struct = rhs_info

        if lhs_is_bundle or rhs_is_bundle:
            # Bundle-to-bundle: create internal wires for each struct field.
            struct_ir = lhs_struct or rhs_struct
            wire_base = lhs_port  # e.g. "io"
            if struct_ir:
                bundle_wire_groups.append(
                    (wire_base, struct_ir, lhs_inst, lhs_port, rhs_inst, rhs_port)
                )
                for sf in struct_ir.fields:
                    wire_name = f"{wire_base}_{sf.name}"
                    internal_wires[wire_name] = _field_bits(sf)
                    if lhs_inst:
                        bound_ports.add((lhs_inst, f"{lhs_port}_{sf.name}"))
                    if rhs_inst:
                        bound_ports.add((rhs_inst, f"{rhs_port}_{sf.name}"))
        elif lhs_inst and not rhs_inst:
            # inst.port ← top.port
            bound_ports.add((lhs_inst, lhs_port))
            inst_port_to_top[(lhs_inst, lhs_port)] = rhs_port
        elif rhs_inst and not lhs_inst:
            bound_ports.add((rhs_inst, rhs_port))
            inst_port_to_top[(rhs_inst, rhs_port)] = lhs_port

    # ------------------------------------------------------------------ #
    # 3. Collect unbound sub-instance ports → expose at top level          #
    # ------------------------------------------------------------------ #
    exposed_ports = []  # (port_name, bits, is_out)
    # Track which names we've already exposed (de-dup)
    exposed_names = set()

    for inst_name, _type_name, sub_ir, sub_py_cls in sub_insts:
        sub_py_meta = {}
        if sub_py_cls and hasattr(sub_py_cls, "__dataclass_fields__"):
            for pf in _dc.fields(sub_py_cls):
                sub_py_meta[pf.name] = pf.metadata

        for sf in sub_ir.fields:
            sft = type(sf).__name__
            if sft == "FieldInOut":
                pname = sf.name
                if (inst_name, pname) not in bound_ports and pname not in exposed_names:
                    bits = _field_bits(sf)
                    is_out = getattr(sf, "is_out", False)
                    exposed_ports.append((pname, bits, is_out))
                    exposed_names.add(pname)
            elif sft == "Field":
                sf_dt = getattr(sf, "datatype", None)
                if sf_dt and type(sf_dt).__name__ == "DataTypeRef":
                    struct_ir = ctx.type_m.get(sf_dt.ref_name)
                    if struct_ir and type(struct_ir).__name__ == "DataTypeStruct":
                        is_mirror = sub_py_meta.get(sf.name, {}).get("kind") == "mirror"
                        for ssf in struct_ir.fields:
                            expanded = f"{sf.name}_{ssf.name}"
                            if (inst_name, expanded) not in bound_ports and expanded not in exposed_names:
                                ssf_is_out = getattr(ssf, "is_out", True)
                                if is_mirror:
                                    ssf_is_out = not ssf_is_out
                                exposed_ports.append((expanded, _field_bits(ssf), ssf_is_out))
                                exposed_names.add(expanded)

    # ------------------------------------------------------------------ #
    # 4. Synthesize sub-components first, then emit the wrapper module.    #
    # ------------------------------------------------------------------ #
    sub_sv_parts = []
    for _inst_name, type_name, sub_ir, sub_py_cls in sub_insts:
        if sub_py_cls is not None:
            sub_sv = _synthesize_sprtl(sub_py_cls, reset_style="sync_low")
            if sub_sv:
                # Strip the common file header so timescale/comment appear once.
                stripped = sub_sv
                for hdr in ("// Generated by zuspec-synth\n", "`timescale 1ns/1ps\n"):
                    stripped = stripped.replace(hdr, "", 1)
                sub_sv_parts.append(stripped.lstrip("\n"))

    all_top_ports = list(top_scalar_ports) + exposed_ports
    port_decls = []
    for pname, bits, is_out in all_top_ports:
        dir_kw = "output" if is_out else "input "
        width_str = _width_str(bits)
        port_decls.append(f"  {dir_kw} logic {width_str}{pname}")

    wrapper_lines = [
        f"module {module_name} (",
        ",\n".join(port_decls),
        ");",
        "",
    ]

    # Internal wire declarations for bundle connections.
    if internal_wires:
        for wname, wbits in internal_wires.items():
            wrapper_lines.append(f"  logic {_width_str(wbits)}{wname};")
        wrapper_lines.append("")

    # Sub-instance instantiations.
    for inst_name, type_name, sub_ir, sub_py_cls in sub_insts:
        sub_py_meta = {}
        if sub_py_cls and hasattr(sub_py_cls, "__dataclass_fields__"):
            for pf in _dc.fields(sub_py_cls):
                sub_py_meta[pf.name] = pf.metadata

        port_conns = []
        for sf in sub_ir.fields:
            sft = type(sf).__name__
            if sft == "FieldInOut":
                pname = sf.name
                if (inst_name, pname) in inst_port_to_top:
                    conn = inst_port_to_top[(inst_name, pname)]
                elif pname in exposed_names:
                    conn = pname  # direct pass-through
                else:
                    conn = pname  # fallback
                port_conns.append(f"    .{pname}({conn})")
            elif sft == "Field":
                sf_dt = getattr(sf, "datatype", None)
                if sf_dt and type(sf_dt).__name__ == "DataTypeRef":
                    struct_ir = ctx.type_m.get(sf_dt.ref_name)
                    if struct_ir and type(struct_ir).__name__ == "DataTypeStruct":
                        for ssf in struct_ir.fields:
                            wire_name = f"{sf.name}_{ssf.name}"
                            port_conns.append(f"    .{sf.name}_{ssf.name}({wire_name})")

        wrapper_lines.append(f"  {type_name} {inst_name}_inst (")
        wrapper_lines.append(",\n".join(port_conns))
        wrapper_lines.append("  );")
        wrapper_lines.append("")

    wrapper_lines.append("endmodule")

    # Combine: file header + sub-component SV + wrapper module.
    header = "// Generated by zuspec-synth\n`timescale 1ns/1ps\n"
    return header + "\n".join(sub_sv_parts) + "\n" + "\n".join(wrapper_lines) + "\n"


def _synthesize_reg_process(component_ir, process_ir, module_name: str) -> str:
    """Emit an always @(posedge clock or posedge reset) module for a @zdc.proc register process.

    Handles the 'while True: await reg.write(...)' pattern. Uses Verilog-2005
    style (reg, always, <=) for Yosys compatibility.
    """
    fields = list(component_ir.fields)
    idx_to_name = {i: f.name for i, f in enumerate(fields)}

    # Collect Reg output fields
    reg_fields = [f for f in fields if getattr(f, 'is_reg', False)]

    # --- Port list ---
    port_lines = ["    input clock", "    input reset"]
    for f in reg_fields:
        bits = _field_bits(f)
        w = f"[{bits-1}:0] " if bits > 1 else ""
        port_lines.append(f"    output reg {w}{f.name}")

    ports = ",\n".join(port_lines)

    lines = [f"module {module_name}(", ports + ");"]
    lines.append("")

    # --- always block ---
    lines.append("  always @(posedge clock or posedge reset) begin")
    lines.append("    if (reset) begin")
    for f in reg_fields:
        rv = f.reset_value if f.reset_value is not None else 0
        lines.append(f"      {f.name} <= {rv};")
    lines.append("    end else begin")

    # Lower the process body — unwrap outer StmtWhile if present
    body_stmts = process_ir.body
    if body_stmts and type(body_stmts[0]).__name__ == "StmtWhile":
        body_stmts = body_stmts[0].body

    body_lines = _ir_stmts_to_sv(body_stmts, idx_to_name, indent=6)
    lines.extend(body_lines)

    lines.append("    end")
    lines.append("  end")
    lines.append("")
    lines.append("endmodule")
    return "\n".join(lines)


def _build_comb_module(component_ir, module_name: str) -> str:
    """Generate a minimal always_comb SV module for a pure-comb component."""
    lines: list[str] = []
    fields = getattr(component_ir, "fields", [])

    # Collect port declarations using is_out (direction is None in DC IR)
    ports: list[str] = []
    output_names: list[str] = []
    # idx_to_name uses enumeration index (same as _synthesize_simple_sync)
    idx_to_name: dict = {i: f.name for i, f in enumerate(fields)}
    for f in fields:
        is_out = getattr(f, "is_out", None)
        if is_out is None:
            continue
        dir_kw = "output" if is_out else "input "
        if is_out:
            output_names.append(f.name)
        bits = _field_bits(f)
        width_str = _width_str(bits)
        ports.append(f"  {dir_kw} logic {width_str}{f.name}")

    port_block = (",\n").join(ports)
    lines.append(f"module {module_name}(")
    lines.append(port_block)
    lines.append(");")
    lines.append("")

    comb_processes = getattr(component_ir, "comb_processes", [])
    for comb_proc in comb_processes:
        lines.append("  always_comb begin")
        # Default-to-zero for all outputs (prevents latches)
        for name in output_names:
            lines.append(f"    {name} = '0;")
        lines.extend(_ir_stmts_to_sv_comb(getattr(comb_proc, "body", []), idx_to_name, 4))
        lines.append("  end")
        lines.append("")

    if not comb_processes:
        lines.append("  always_comb begin")
        for name in output_names:
            lines.append(f"    {name} = '0;")
        lines.append("  end")
        lines.append("")

    lines.append("endmodule")

    return "\n".join(lines) + "\n"


__all__ = ["sprtl", "synthesize", "ActionSynthConfig", "synth_action"]


# ---------------------------------------------------------------------------
# Constraint-action synthesis API
# ---------------------------------------------------------------------------

from dataclasses import dataclass as _dc, field as _field
from typing import Optional as _Opt, List as _List, Tuple as _Tuple


@_dc
class ActionSynthConfig:
    """Configuration for :func:`synth_action`.

    Pass an instance to :func:`synth_action` to control which optimisation
    passes run and how the output module is named.  All fields have sensible
    defaults so the common case requires no arguments::

        sv = synth_action(MyDecodeAction)                          # all passes
        sv = synth_action(MyDecodeAction, ActionSynthConfig(odc=False))  # SOP only

    Attributes
    ----------
    odc : bool
        Enable Observability Don't-Care minimisation (``build_odc_cubes``).
        Requires at least one ``zdc.valid()`` annotation on the action class to
        have any effect; safe to enable even when none are present.
        Default: ``True``.
    top : str or None
        Override the generated module name.  When ``None`` (default) the
        module is named after the action class (``cls.__name__``).
    prefix : str
        RTL wire-name prefix used inside the generated module body.
        Default: ``""`` (no prefix).
    warn_only : bool
        When ``True`` (default), validation problems are emitted as warnings
        rather than raising an exception.
    """
    odc: bool = True
    top: _Opt[str] = None
    prefix: str = ""
    warn_only: bool = True


def synth_action(cls: type,
                 config: _Opt[ActionSynthConfig] = None,
                 *,
                 output: _Opt[str] = None) -> str:
    """Synthesize a constraint-action class to a stand-alone SystemVerilog module.

    This is the primary entry point for the constraint-to-RTL pipeline.  It
    runs the full pass chain (extract → compute_support → validate →
    build_cubes → [build_odc_cubes] → minimize → emit_sv) and wraps the
    result in a self-contained ``module … endmodule`` block.

    Parameters
    ----------
    cls:
        A Python class decorated with ``@zdc.dataclass`` that has
        ``@constraint`` methods and ``zdc.rand()`` output fields.
    config:
        An :class:`ActionSynthConfig` instance.  When omitted all passes are
        enabled with default settings.
    output:
        Optional file path.  When given the SV text is also written there.

    Returns
    -------
    str
        The complete SystemVerilog module text.

    Example
    -------
    ::

        from zuspec.synth import synth_action, ActionSynthConfig
        import zuspec.dataclasses as zdc
        from zuspec.dataclasses import constraint

        @zdc.dataclass
        class Decode(zdc.Action):
            instr : zdc.u32 = zdc.input()
            _op   : zdc.u7  = zdc.rand()   # internal: _ prefix
            out   : zdc.u4  = zdc.rand()

            @constraint
            def c_op(self):
                assert self._op == (self.instr & 0x7F)

            @constraint
            def c_out(self):
                if self._op == 0x33:
                    assert self.out == 0

        print(synth_action(Decode))
    """
    from zuspec.synth.sprtl.constraint_compiler import ConstraintCompiler

    if config is None:
        config = ActionSynthConfig()

    top_name = config.top or cls.__name__

    cc = ConstraintCompiler(cls, prefix=config.prefix)
    cc.extract()
    cc.compute_support()
    cc.validate(warn_only=config.warn_only)
    cc.build_cubes()
    if config.odc:
        cc.build_odc_cubes()
    cc.minimize()
    body_lines = cc.emit_sv()

    # Determine port lists from compiler state.
    internal = set(cc.cset.internal_fields)

    input_ports: _List[_Tuple[str, int]] = [(cc.cset.input_field, cc.cset.input_width)]
    output_ports: _List[_Tuple[str, int]] = [
        (f.name, f.width) for f in cc.cset.output_fields if f.name not in internal
    ]

    def _port_decl(ins: _List[_Tuple[str, int]], outs: _List[_Tuple[str, int]]) -> str:
        lines = []
        for name, w in ins:
            if w == 1:
                lines.append(f"    input  logic        {name}")
            else:
                lines.append(f"    input  logic [{w-1}:0]  {name}")
        for name, w in outs:
            if w == 1:
                lines.append(f"    output logic        {name}")
            else:
                lines.append(f"    output logic [{w-1}:0]  {name}")
        return ",\n".join(lines)

    sv_lines = [
        f"// {top_name} — constraint-synthesized by zuspec.synth.synth_action",
        f"// odc={config.odc}",
        "",
        f"module {top_name} (",
        _port_decl(input_ports, output_ports),
        ");",
        "",
    ]
    for line in body_lines:
        sv_lines.append(f"    {line}")
    sv_lines.append("")
    sv_lines.append("    // Connect internal wires to output ports.")
    for name, _ in output_ports:
        sv_lines.append(f"    assign {name} = _{name};")
    sv_lines.extend(["", "endmodule", ""])

    sv_text = "\n".join(sv_lines)

    if output is not None:
        import pathlib
        pathlib.Path(output).parent.mkdir(parents=True, exist_ok=True)
        pathlib.Path(output).write_text(sv_text)

    return sv_text
