"""
zuspec.synth.mls — Internal SV/cert codegen helpers for zuspec-synth.

Public synthesis API is exposed through the named pass classes in
``zuspec.synth.passes`` (ElaboratePass, FSMExtractPass, SchedulePass,
LowerPass, SVEmitPass, CertEmitPass) via ``zuspec.dataclasses.transform.PassManager``.

This module contains only private code-generation helpers used by those passes.
"""
from __future__ import annotations

import json
import logging
import os
from typing import Any, List, Optional, Tuple

import datetime

from .elab.lowerer import Lowerer
from .ir.pipeline_ir import PipelineIR
from .verify import deadlock as _deadlock_mod
from .sprtl.fsm_ir import FSMModule, FSMState, FSMStateKind

log = logging.getLogger(__name__)


def _pfx(prefix: str, name: str) -> str:
    """Return '{prefix}_{name}' when prefix is non-empty, else '{name}'."""
    return f'{prefix}_{name}' if prefix else name


_STAGE_NAMES = {
    1: ["EXECUTE"],
    2: ["FETCH", "EXECUTE"],
    3: ["FETCH", "DECODE", "EXECUTE"],
    4: ["FETCH", "DECODE", "EXECUTE", "WRITEBACK"],
    5: ["FETCH", "DECODE", "REG_READ", "EXECUTE", "WRITEBACK"],
    6: ["FETCH", "DECODE", "REG_READ", "EXECUTE", "MEM_ACCESS", "WRITEBACK"],
    7: ["FETCH", "DECODE", "REG_READ", "ISSUE_A", "ISSUE_B", "EXECUTE", "WRITEBACK"],
}


def _generate_sv_from_meta(ir, pipeline_stages: int = 2) -> str:
    """Generate Verilog 2005 (IEEE 1364-2005) for the component described in *ir*.

    Uses only plain Verilog 2005 constructs for Yosys compatibility:
    - ``wire``/``reg`` instead of ``logic``
    - ``localparam`` state encoding instead of ``typedef enum``
    - ``always @(*)`` instead of ``always_comb``
    - ``always @(posedge …)`` instead of ``always_ff``

    Args:
        ir: SynthIR-compatible object with ``component`` and ``config`` fields.
        pipeline_stages: Number of pipeline stages to encode.
    """
    import math

    comp_name = getattr(ir.component, '__name__', 'Component') if ir.component else 'Component'

    # Derive isa_spec from config
    isa_str = ''
    if hasattr(ir.config, 'isa_spec'):
        isa_str = f'_{ir.config.isa_spec()}'

    module_name = f'{comp_name}{isa_str}'

    stages = _STAGE_NAMES.get(pipeline_stages, [f'S{i}' for i in range(pipeline_stages)])
    n_states = len(stages)
    width = max(1, math.ceil(math.log2(n_states + 1))) if n_states > 1 else 1

    lines = []
    lines.append(f'// Auto-generated by zuspec-synth  (component={comp_name}, config={ir.config!r})')
    lines.append(f'// Verilog 2005 (IEEE 1364-2005) — Yosys compatible')
    lines.append(f'`timescale 1ns/1ps')
    lines.append(f'// Pipeline stages: {pipeline_stages}  States: {stages}')
    lines.append(f'module {module_name} (')
    lines.append(f'  input  wire clk,')
    lines.append(f'  input  wire rst_n')
    lines.append(f');')
    lines.append(f'')

    # State encoding via localparam
    lines.append(f'  // State encoding')
    for i, s in enumerate(stages):
        lines.append(f"  localparam [{width - 1}:0] {s} = {width}'d{i};")
    lines.append(f'')

    lines.append(f'  reg [{width - 1}:0] state;')
    lines.append(f'  reg [{width - 1}:0] next_state;')
    lines.append(f'')

    # Sequential state register (async active-low reset)
    lines.append(f'  always @(posedge clk or negedge rst_n) begin')
    lines.append(f'    if (!rst_n) state <= {stages[0]};')
    lines.append(f'    else        state <= next_state;')
    lines.append(f'  end')
    lines.append(f'')

    # Combinational next-state logic
    lines.append(f'  always @(*) begin')
    lines.append(f'    next_state = state;')
    lines.append(f'    case (state)')
    for i, s in enumerate(stages):
        next_s = stages[(i + 1) % len(stages)]
        lines.append(f'      {s}: next_state = {next_s};')
    lines.append(f'      default: next_state = state;')
    lines.append(f'    endcase')
    lines.append(f'  end')
    lines.append(f'')
    lines.append(f'endmodule')
    return '\n'.join(lines) + '\n'


# ---------------------------------------------------------------------------
# Pipeline SV codegen (Phase 2)
# ---------------------------------------------------------------------------

import os as _os
_THIS_DIR = _os.path.dirname(_os.path.abspath(__file__))
_TEMPLATE_DIR = _os.path.join(_THIS_DIR, 'templates')


def _read_fifo_template() -> str:
    path = _os.path.join(_TEMPLATE_DIR, 'fifo_sync.v')
    with open(path) as fh:
        return fh.read()


def _read_skid_template() -> str:
    path = _os.path.join(_TEMPLATE_DIR, 'skid_buffer.v')
    with open(path) as fh:
        return fh.read()


# Channels with depth > this threshold use skid_buffer instead of fifo_sync.
_SKID_DEPTH_THRESHOLD = 2


# ---------------------------------------------------------------------------
# Verilog 2005 helpers
# ---------------------------------------------------------------------------

def _vr(count, value):
    """Verilog replication: {count{value}}"""
    return '{' + str(count) + '{' + value + '}}'


def _vc(*args):
    """Verilog concatenation: {a, b, ...}"""
    return '{' + ', '.join(str(a) for a in args) + '}'


def _get_xlen(ir: Any) -> int:
    """Extract xlen from ir.config, default 32."""
    cfg = getattr(ir, 'config', None) if ir else None
    if cfg is None:
        return 32
    return getattr(cfg, 'xlen', 32)


def _get_reset_addr(ir: Any) -> int:
    """Extract reset_addr from ir.config, default 0."""
    cfg = getattr(ir, 'config', None) if ir else None
    if cfg is None:
        return 0
    return getattr(cfg, 'reset_addr', 0)


def _get_pipeline_stages(ir: Any) -> int:
    """Get number of pipeline stages from ir passes."""
    for pname, pkwargs in reversed(getattr(ir, 'passes', [])):
        if pname == 'schedule' and 'pipeline_stages' in pkwargs:
            return pkwargs['pipeline_stages']
    return 2


def _get_method_port(ir: Any, name: str):
    """Return the MethodPortDecl with *name* from ``ir.meta``, or ``None``."""
    meta = getattr(ir, 'meta', None)
    if meta is None:
        return None
    for mp in getattr(meta, 'method_ports', []):
        if mp.name == name:
            return mp
    return None


def _emit_ports(lines: List[str], ports: List[Tuple[str, str, str, str]]) -> None:
    for i, (pdir, ptype, pwidth, pname) in enumerate(ports):
        comma = '' if i == len(ports) - 1 else ','
        w = f' {pwidth}' if pwidth else ''
        lines.append(f'  {pdir:<6} {ptype:<4}{w} {pname}{comma}')



def _gen_regfile_module(xlen: int, module_prefix: str = "") -> List[str]:
    """Generate Verilog 2005 regfile_rv module."""
    L: List[str] = []
    L.append(f'// {"=" * 60}')
    L.append(f'// {_pfx(module_prefix, "regfile_rv")} — synchronous register file')
    L.append(f'// {"=" * 60}')
    L.append(f'module {_pfx(module_prefix, "regfile_rv")} #(parameter XLEN = 32) (')
    L.append(f'  input  wire              clk,')
    L.append(f'  input  wire              rst_n,')
    L.append(f'  input  wire [4:0]        rs1_addr,')
    L.append(f'  output wire [XLEN-1:0]   rs1_data,')
    L.append(f'  input  wire [4:0]        rs2_addr,')
    L.append(f'  output wire [XLEN-1:0]   rs2_data,')
    L.append(f'  input  wire [4:0]        rd_addr,')
    L.append(f'  input  wire [XLEN-1:0]   rd_data,')
    L.append(f'  input  wire              rd_we')
    L.append(f');')
    L.append(f"  reg [XLEN-1:0] regs [0:31];")
    L.append("  assign rs1_data = (rs1_addr == 5'b0) ? {XLEN{1'b0}} : regs[rs1_addr];")
    L.append("  assign rs2_data = (rs2_addr == 5'b0) ? {XLEN{1'b0}} : regs[rs2_addr];")
    L.append(f'  always @(posedge clk) begin')
    L.append(f"    if (rd_we && rd_addr != 5'b0)")
    L.append(f'      regs[rd_addr] <= rd_data;')
    L.append(f'  end')
    L.append(f'endmodule')
    L.append(f'')
    return L


def _gen_payload_typedefs(xlen: int, module_prefix: str = "") -> List[str]:
    """Generate compile-unit-scope packed struct typedefs for channel payloads."""
    L: List[str] = []
    L.append('// ── Channel payload typedefs ─────────────────────────────')
    L.append('// Fields listed MSB-first (packed struct convention).')
    L.append('// Bit layouts match channel_payload_width() in lowerer.py.')
    L.append('')
    # fetch_pld_t: {insn[31:0], pc[xlen-1:0]}  total = xlen+32
    L.append('typedef struct packed {')
    L.append(f'  logic [31:0]       insn;')
    L.append(f'  logic [{xlen-1}:0] pc;')
    L.append(f'}} {_pfx(module_prefix, "fetch_pld_t")};')
    L.append('')
    # decode_pld_t: {imm, optype, funct7, funct3, rs2, rs1, rd, insn, pc}  total = 2*xlen+67
    L.append('typedef struct packed {')
    L.append(f'  logic [{xlen-1}:0] imm;')
    L.append(f'  logic [9:0]        optype;')
    L.append(f'  logic [6:0]        funct7;')
    L.append(f'  logic [2:0]        funct3;')
    L.append(f'  logic [4:0]        rs2;')
    L.append(f'  logic [4:0]        rs1;')
    L.append(f'  logic [4:0]        rd;')
    L.append(f'  logic [31:0]       insn;')
    L.append(f'  logic [{xlen-1}:0] pc;')
    L.append(f'}} {_pfx(module_prefix, "decode_pld_t")};')
    L.append('')
    # rread_pld_t: {rs2_val, rs1_val, imm, optype, funct7, funct3, rs2, rs1, rd, insn, pc}  total = 4*xlen+67
    L.append('typedef struct packed {')
    L.append(f'  logic [{xlen-1}:0] rs2_val;')
    L.append(f'  logic [{xlen-1}:0] rs1_val;')
    L.append(f'  logic [{xlen-1}:0] imm;')
    L.append(f'  logic [9:0]        optype;')
    L.append(f'  logic [6:0]        funct7;')
    L.append(f'  logic [2:0]        funct3;')
    L.append(f'  logic [4:0]        rs2;')
    L.append(f'  logic [4:0]        rs1;')
    L.append(f'  logic [4:0]        rd;')
    L.append(f'  logic [31:0]       insn;')
    L.append(f'  logic [{xlen-1}:0] pc;')
    L.append(f'}} {_pfx(module_prefix, "rread_pld_t")};')
    L.append('')
    # exec_pld_t: {branch_target, branch_taken, we, result, rd}  total = 2*xlen+7
    L.append('typedef struct packed {')
    L.append(f'  logic [{xlen-1}:0] branch_target;')
    L.append(f'  logic              branch_taken;')
    L.append(f'  logic              we;')
    L.append(f'  logic [{xlen-1}:0] result;')
    L.append(f'  logic [4:0]        rd;')
    L.append(f'}} {_pfx(module_prefix, "exec_pld_t")};')
    L.append('')
    return L


def _payload_type(width: int, xlen: int, module_prefix: str = "") -> Optional[str]:
    """Return the packed struct type name for a channel of *width* bits, or None."""
    if width == xlen + 32:    return _pfx(module_prefix, 'fetch_pld_t')
    if width == 2*xlen + 67:  return _pfx(module_prefix, 'decode_pld_t')
    if width == 4*xlen + 67:  return _pfx(module_prefix, 'rread_pld_t')
    if width == 2*xlen + 7:   return _pfx(module_prefix, 'exec_pld_t')
    return None


def _gen_stage_module_generic(stage: Any, module_prefix: str = "") -> List[str]:
    """Generic fallback stage module for unrecognised stage names.

    Used when ``ir.stage_sv`` does not contain a pre-generated entry for the
    stage (i.e. no plugin pass has generated it).  Produces a structurally
    valid but body-less SV module.
    """
    name = stage.name
    lines: List[str] = []
    lines.append(f'// {"=" * 60}')
    lines.append(f'// {name}')
    lines.append(f'// {"=" * 60}')
    lines.append(f'module {_pfx(module_prefix, name)} (')
    ports: List[Tuple[str, str, str, str]] = []
    ports.append(('input',  'wire', '', 'clk'))
    ports.append(('input',  'wire', '', 'rst_n'))
    for ch in stage.inputs:
        W = ch.width
        ports.append(('input',  'wire', f'[{W-1}:0]', f'{ch.name}_data'))
        ports.append(('input',  'wire', '',            f'{ch.name}_vld'))
        ports.append(('output', 'reg',  '',            f'{ch.name}_rdy'))
    for ch in stage.outputs:
        W = ch.width
        ports.append(('output', 'reg',  f'[{W-1}:0]', f'{ch.name}_raw'))
        ports.append(('output', 'reg',  '',            f'{ch.name}_raw_vld'))
        ports.append(('input',  'wire', '',            f'{ch.name}_full'))
    for pd in stage.ports:
        W = pd.width
        vtype = 'reg' if pd.direction == 'output' else 'wire'
        wspec = f'[{W-1}:0]' if W > 1 else ''
        ports.append((pd.direction, vtype, wspec, pd.name))
    _emit_ports(lines, ports)
    lines.append(');')
    lines.append('  always @(posedge clk or negedge rst_n) begin')
    lines.append("    if (!rst_n) begin")
    for ch in stage.inputs:
        lines.append(f"      {ch.name}_rdy <= 1'b1;")
    for ch in stage.outputs:
        lines.append(f"      {ch.name}_raw_vld <= 1'b0;")
    lines.append("    end else begin")
    if stage.inputs and stage.outputs:
        in_ch = stage.inputs[0]; out_ch = stage.outputs[0]
        lines.append(f"      {in_ch.name}_rdy <= !{out_ch.name}_full;")
        lines.append(f"      if ({in_ch.name}_vld && {in_ch.name}_rdy) begin")
        lines.append(f"        {out_ch.name}_raw     <= {in_ch.name}_data;")
        lines.append(f"        {out_ch.name}_raw_vld <= 1'b1;")
        lines.append(f"      end else begin")
        lines.append(f"        {out_ch.name}_raw_vld <= 1'b0;")
        lines.append(f"      end")
    lines.append("    end")
    lines.append("  end")
    lines.append('')
    lines.append('endmodule')
    lines.append('')
    return lines


def _gen_toplevel(pipeline_ir: Any, ir: Any = None, module_prefix: str = "") -> List[str]:
    """Generate the top-level wrapper module that instantiates all stages and FIFOs."""
    mod = pipeline_ir.module_name
    xlen = _get_xlen(ir) if ir is not None else 32
    n_stages = pipeline_ir.pipeline_stages

    stage_names = {s.name for s in pipeline_ir.stages}
    has_writeback = 'WriteBackStage' in stage_names
    has_regread   = 'RegReadStage' in stage_names

    # Determine regfile module name and whether to use elaborated port names
    meta = getattr(ir, 'meta', None) if ir is not None else None
    regfile_decl  = (meta.regfiles[0]  if meta and getattr(meta, 'regfiles',      None) else None)
    pool_decl     = (meta.indexed_pools[0] if meta and getattr(meta, 'indexed_pools', None) else None)
    has_scoreboard = has_regread and pool_decl is not None

    if regfile_decl is not None:
        rf_module_name = (
            f'{regfile_decl.field_name}_1p'   if regfile_decl.shared_port else
            f'{regfile_decl.field_name}_sdp'  if regfile_decl.read_ports == 1 else
            f'{regfile_decl.field_name}_{regfile_decl.read_ports}r{regfile_decl.write_ports}w'
        )
        rf_aw = regfile_decl.idx_width
        rf_dw = regfile_decl.data_width
        rf_depth = regfile_decl.depth
    else:
        rf_module_name = _pfx(module_prefix, 'regfile_rv')
        rf_aw = 5; rf_dw = xlen; rf_depth = 32

    lines: List[str] = []
    lines.append(f'// {"=" * 60}')
    lines.append(f'// {mod} — top-level pipeline wrapper')
    lines.append(f'// {"=" * 60}')

    # Collect all external ports from all stages
    all_ext_ports = [pd for stage in pipeline_ir.stages for pd in stage.ports]

    # Build top-level port declarations
    top_ports = ['  input wire clk', '  input wire rst_n']
    for pd in all_ext_ports:
        W = pd.width
        wspec = f'[{W-1}:0] ' if W > 1 else ''
        vdir = 'output wire' if pd.direction == 'output' else 'input  wire'
        top_ports.append(f'  {vdir} {wspec}{pd.name}')

    lines.append(f'module {_pfx(module_prefix, mod)} (')
    for i, p in enumerate(top_ports):
        comma = '' if i == len(top_ports) - 1 else ','
        lines.append(f'{p}{comma}')
    lines.append(f');')
    lines.append('')

    # Branch feedback wires
    lines.append(f'  // Branch feedback')
    lines.append(f'  wire            branch_taken;')
    lines.append(f'  wire [{xlen-1}:0] branch_target;')
    lines.append('')

    # Regfile connection wires (5-stage)
    if has_regread:
        lines.append(f'  // Register file connections')
        lines.append(f'  wire [{rf_aw-1}:0]    rf_rs1_addr;')
        lines.append(f'  wire [{rf_dw-1}:0]    rf_rs1_data;')
        lines.append(f'  wire [{rf_aw-1}:0]    rf_rs2_addr;')
        lines.append(f'  wire [{rf_dw-1}:0]    rf_rs2_data;')
        lines.append(f'  wire [{rf_aw-1}:0]    rf_rd_addr;')
        lines.append(f'  wire [{rf_dw-1}:0]    rf_rd_data;')
        lines.append(f'  wire                  rf_rd_we;')
        lines.append('')

    # Scoreboard connection wires (when an IndexedPool is declared)
    if has_scoreboard:
        aw = pool_decl.idx_width
        lines.append(f'  // Scoreboard connections ({pool_decl.field_name})')
        lines.append(f'  wire              sb_hazard;')
        lines.append(f'  wire              sb_set_we;')
        lines.append(f'  wire [{aw-1}:0]   sb_set_idx;')
        lines.append(f'  wire [{aw-1}:0]   sb_rs1_idx;')
        lines.append(f'  wire [{aw-1}:0]   sb_rs2_idx;')
        lines.append('')

    # Wire declarations for each channel
    for ch in pipeline_ir.channels:
        cn = ch.name
        W  = ch.width
        use_skid = ch.depth > _SKID_DEPTH_THRESHOLD
        st = _payload_type(W, xlen, module_prefix)
        wtype = st if st else f'[{W-1}:0]'
        lines.append(f'  // Channel: {cn}  ({_pfx(module_prefix, "skid_buffer") if use_skid else _pfx(module_prefix, "fifo_sync")}, depth={ch.depth})')
        lines.append(f'  wire {wtype} {cn}_raw;')
        lines.append(f'  wire            {cn}_raw_vld;')
        lines.append(f'  wire            {cn}_full;')
        lines.append(f'  wire {wtype} {cn}_data;')
        lines.append(f'  wire            {cn}_vld;')
        lines.append(f'  wire            {cn}_rdy;')
        if use_skid:
            lines.append(f'  wire            {cn}_s_ready;')
        else:
            lines.append(f'  wire            {cn}_wr_en;')
            lines.append(f'  wire            {cn}_empty;')
        lines.append('')

    # Assign derived signals
    for ch in pipeline_ir.channels:
        cn = ch.name
        use_skid = ch.depth > _SKID_DEPTH_THRESHOLD
        if use_skid:
            lines.append(f'  assign {cn}_full = ~{cn}_s_ready;')
            lines.append(f'  // {cn}_vld driven by skid_buffer m_valid directly')
        else:
            lines.append(f'  assign {cn}_wr_en = {cn}_raw_vld & ~{cn}_full;')
            # Gate valid with branch_taken so ExecuteStage discards misspeculated instructions
            lines.append(f'  assign {cn}_vld   = ~{cn}_empty & ~branch_taken;')
    if pipeline_ir.channels:
        lines.append('')

    # Buffer instances
    for ch in pipeline_ir.channels:
        cn = ch.name
        W  = ch.width
        use_skid = ch.depth > _SKID_DEPTH_THRESHOLD
        if use_skid:
            lines.append(f'  {_pfx(module_prefix, "skid_buffer")} #(.WIDTH({W})) u_{cn}_buf (')
            lines.append(f'    .clk      (clk),')
            lines.append(f'    .rst_n    (rst_n),')
            lines.append(f'    .s_valid  ({cn}_raw_vld),')
            lines.append(f'    .s_data   ({cn}_raw),')
            lines.append(f'    .s_ready  ({cn}_s_ready),')
            lines.append(f'    .m_valid  ({cn}_vld),')
            lines.append(f'    .m_data   ({cn}_data),')
            lines.append(f'    .m_ready  ({cn}_rdy)')
            lines.append(f'  );')
        else:
            st = _payload_type(W, xlen, module_prefix)
            lines.append(f'  {_pfx(module_prefix, "fifo_sync")} #(.WIDTH({W}), .DEPTH({ch.depth})) u_{cn}_fifo (')
            lines.append(f'    .clk   (clk),')
            lines.append(f'    .rst_n (rst_n),')
            lines.append(f'    .flush (branch_taken),')
            lines.append(f'    .wr_en ({cn}_wr_en),')
            lines.append(f'    .din   ({cn}_raw),')
            lines.append(f'    .dout  ({cn}_data),')
            lines.append(f'    .full  ({cn}_full),')
            lines.append(f'    .empty ({cn}_empty),')
            lines.append(f'    .rd_en ({cn}_rdy)')
            lines.append(f'  );')
        lines.append('')

    # Regfile instance (5-stage) — use elaborated port names when available
    if has_regread:
        if regfile_decl is not None and not regfile_decl.shared_port:
            # Elaborated topology: use rp{N}_addr / wp{N}_addr port names
            lines.append(f'  {_pfx(module_prefix, rf_module_name)} #(')
            lines.append(f'    .DEPTH({rf_depth}), .IDX_WIDTH({rf_aw}), .DATA_WIDTH({rf_dw})')
            lines.append(f'  ) u_regfile (')
            lines.append(f'    .clk      (clk),')
            for rp in range(regfile_decl.read_ports):
                rp_addr = 'rf_rs1_addr' if rp == 0 else 'rf_rs2_addr'
                rp_data = 'rf_rs1_data' if rp == 0 else 'rf_rs2_data'
                lines.append(f'    .rp{rp}_addr ({rp_addr}),')
                lines.append(f'    .rp{rp}_data ({rp_data}),')
            for wp in range(regfile_decl.write_ports):
                lines.append(f'    .wp{wp}_addr (rf_rd_addr),')
                lines.append(f'    .wp{wp}_data (rf_rd_data),')
                comma = '' if wp == regfile_decl.write_ports - 1 else ','
                lines.append(f'    .wp{wp}_we   (rf_rd_we){comma}')
            lines.append(f'  );')
        else:
            # Fallback: hardcoded regfile_rv port names
            lines.append(f'  {rf_module_name} #(.XLEN({xlen})) u_regfile (')
            lines.append(f'    .clk      (clk),')
            lines.append(f'    .rst_n    (rst_n),')
            lines.append(f'    .rs1_addr (rf_rs1_addr),')
            lines.append(f'    .rs1_data (rf_rs1_data),')
            lines.append(f'    .rs2_addr (rf_rs2_addr),')
            lines.append(f'    .rs2_data (rf_rs2_data),')
            lines.append(f'    .rd_addr  (rf_rd_addr),')
            lines.append(f'    .rd_data  (rf_rd_data),')
            lines.append(f'    .rd_we    (rf_rd_we)')
            lines.append(f'  );')
        lines.append('')

    # Scoreboard instance
    if has_scoreboard:
        sb_name = _pfx(module_prefix, f'{pool_decl.field_name}_scoreboard')
        aw = pool_decl.idx_width
        noop = pool_decl.noop_idx if pool_decl.noop_idx is not None else 0
        lines.append(f'  {sb_name} #(')
        lines.append(f'    .DEPTH({pool_decl.depth}), .IDX_WIDTH({aw}), .NOOP_IDX({noop})')
        lines.append(f'  ) u_scoreboard (')
        lines.append(f'    .clk        (clk),')
        lines.append(f'    .rst_n      (rst_n),')
        lines.append(f'    .set_we     (sb_set_we),')
        lines.append(f'    .set_idx    (sb_set_idx),')
        lines.append(f'    .clear_we   (rf_rd_we),')
        lines.append(f'    .clear_idx  (rf_rd_addr),')
        lines.append(f'    .query0_idx (sb_rs1_idx),')
        lines.append(f'    .query1_idx (sb_rs2_idx),')
        lines.append(f'    .hazard     (sb_hazard)')
        lines.append(f'  );')
        lines.append('')

    # Stage instances
    for stage in pipeline_ir.stages:
        inst = f'u_{stage.name.lower()}'
        lines.append(f'  {_pfx(module_prefix, stage.name)} {inst} (')
        conns: List[Tuple[str, str]] = [('clk', 'clk'), ('rst_n', 'rst_n')]
        for ch in stage.inputs:
            cn = ch.name
            conns += [(f'{cn}_data', f'{cn}_data'), (f'{cn}_vld', f'{cn}_vld'),
                      (f'{cn}_rdy',  f'{cn}_rdy')]
        for ch in stage.outputs:
            cn = ch.name
            conns += [(f'{cn}_raw',     f'{cn}_raw'),
                      (f'{cn}_raw_vld', f'{cn}_raw_vld'),
                      (f'{cn}_full',    f'{cn}_full')]
        # External bundle ports pass through with the same name
        for pd in stage.ports:
            conns.append((pd.name, pd.name))
        # Branch feedback ports
        if stage.name == 'FetchStage':
            conns.append(('branch_taken',  'branch_taken'))
            conns.append(('branch_target', 'branch_target'))
        elif stage.name == 'ExecuteStage' and not has_writeback:
            conns.append(('branch_taken',  'branch_taken'))
            conns.append(('branch_target', 'branch_target'))
        elif stage.name == 'WriteBackStage':
            conns.append(('branch_taken',  'branch_taken'))
            conns.append(('branch_target', 'branch_target'))
            if has_regread:
                conns.append(('rd_addr', 'rf_rd_addr'))
                conns.append(('rd_data', 'rf_rd_data'))
                conns.append(('rd_we',   'rf_rd_we'))
        elif stage.name == 'RegReadStage':
            conns.append(('rs1_addr', 'rf_rs1_addr'))
            conns.append(('rs2_addr', 'rf_rs2_addr'))
            conns.append(('rs1_data', 'rf_rs1_data'))
            conns.append(('rs2_data', 'rf_rs2_data'))
            # Scoreboard hazard interface — tie off when no pool declared
            if has_scoreboard:
                conns.append(('hazard',    'sb_hazard'))
                conns.append(('ex_rd_we',  'sb_set_we'))
                conns.append(('ex_rd',     'sb_set_idx'))
                conns.append(('ex_rs1',    'sb_rs1_idx'))
                conns.append(('ex_rs2',    'sb_rs2_idx'))
            else:
                conns.append(('hazard',    "1'b0"))
        for i, (pname, cname) in enumerate(conns):
            comma = '' if i == len(conns) - 1 else ','
            lines.append(f'    .{pname:<28} ({cname}){comma}')
        lines.append('  );')
        lines.append('')

    lines.append('endmodule')
    return lines


def _generate_pipeline_sv(ir: Any, module_prefix: str = "") -> str:
    """Generate a multi-module SystemVerilog pipeline file from ``ir.pipeline_ir``."""
    pip = ir.pipeline_ir
    comp_name = getattr(ir.component, '__name__', 'Component') if ir.component else 'Component'
    xlen = _get_xlen(ir)
    n_stages = pip.pipeline_stages

    out: List[str] = []
    out.append('/* verilator lint_off MULTITOP */')
    out.append(f'// Auto-generated by zuspec-synth  (component={comp_name}, config={ir.config!r})')
    out.append(f'// SystemVerilog (IEEE 1800-2017) — Yosys/Verilator compatible')
    out.append(f'`timescale 1ns/1ps')
    out.append(f'// Pipeline: {pip.pipeline_stages} stages — '
               + ', '.join(s.name for s in pip.stages))
    out.append('')

    # Payload struct typedefs (compile-unit scope, before any module)
    out.extend(_gen_payload_typedefs(xlen, module_prefix))

    # Embed the fifo_sync template (always needed for shallow channels)
    try:
        fifo_text = _read_fifo_template()
        if module_prefix:
            fifo_text = fifo_text.replace('module fifo_sync', f'module {_pfx(module_prefix, "fifo_sync")}', 1)
        out.append(fifo_text)
    except OSError as exc:
        log.warning("[mls] could not read fifo_sync.v: %s", exc)

    # Embed skid_buffer template only when at least one channel is deep
    has_deep = any(ch.depth > _SKID_DEPTH_THRESHOLD for ch in pip.channels)
    if has_deep:
        try:
            skid_text = _read_skid_template()
            if module_prefix:
                skid_text = skid_text.replace('module skid_buffer', f'module {_pfx(module_prefix, "skid_buffer")}', 1)
            out.append(skid_text)
        except OSError as exc:
            log.warning("[mls] could not read skid_buffer.v: %s", exc)

    # Emit register file module when there is a RegReadStage (5-stage+).
    # Prefer the elaborated topology from ir.meta; fall back to the
    # hardcoded 2R/1W module when meta is unavailable.
    stage_names = {s.name for s in pip.stages}
    if 'RegReadStage' in stage_names:
        meta = getattr(ir, 'meta', None)
        if meta is not None and getattr(meta, 'regfiles', None):
            from .sprtl.sv_codegen import generate_regfile_sv
            rf_sv = generate_regfile_sv(meta, module_prefix=module_prefix)
            if rf_sv:
                out.append(rf_sv)
                out.append('')
        else:
            out.extend(_gen_regfile_module(xlen, module_prefix))

    # Emit IndexedPool scoreboard module(s) only for 5-stage pipelines that
    # include a RegReadStage.  For 2-stage pipelines the scoreboard is not
    # instantiated (_gen_toplevel uses has_scoreboard = has_regread && pool), so
    # emitting the module would create an orphan top-level that Verilator rejects.
    meta = getattr(ir, 'meta', None)
    if meta is not None and getattr(meta, 'indexed_pools', None) and 'RegReadStage' in stage_names:
        from .sprtl.indexed_pool_synth import IndexedPoolHazardAnalyzer, IndexedPoolSVGenerator
        _analyzer  = IndexedPoolHazardAnalyzer()
        _pool_gen  = IndexedPoolSVGenerator()
        for pool_decl in meta.indexed_pools:
            pool_hazards = _analyzer.analyze(pool_decl)
            out.append(_pool_gen.generate(pool_decl, pool_hazards, module_prefix=module_prefix))
            out.append('')

    # One module per stage.
    # Prefer pre-generated SV from ir.stage_sv (populated by RVStageGeneratePass
    # or any other plugin pass); fall back to the generic stub for unknown stages.
    stage_sv_map = getattr(ir, 'stage_sv', {})
    for stage in pip.stages:
        if stage.name in stage_sv_map:
            out.extend(stage_sv_map[stage.name])
        else:
            out.extend(_gen_stage_module_generic(stage, module_prefix))

    # Top-level wrapper
    out.extend(_gen_toplevel(pip, ir, module_prefix))
    out.append('/* verilator lint_on MULTITOP */')
    out.append('')

    return '\n'.join(out)
