# Copyright 2019-2026 Matthew Ballance and contributors
# SPDX-License-Identifier: Apache-2.0
"""Tests for ModuleAssemblePythonPass — Phase 4 of IR→Python round-trip."""
import sys
import os
import pytest

_this_dir = os.path.dirname(os.path.abspath(__file__))
_synth_src = os.path.join(_this_dir, "..", "src")
_dc_src = os.path.join(_this_dir, "..", "..", "zuspec-dataclasses", "src")
_blinky_dir = os.path.join(_this_dir, "..", "..", "..", "design", "spl", "blinky")
_rotate_dir = os.path.join(_this_dir, "..", "..", "..", "design", "spl", "rotate")

for _p in (_synth_src, _dc_src, _blinky_dir, _rotate_dir):
    if _p not in sys.path:
        sys.path.insert(0, _p)

from zuspec.dataclasses.data_model_factory import DataModelFactory
from zuspec.synth.passes.component_fields import ComponentFieldsPass
from zuspec.synth.passes.process_to_fsm import ProcessToFSMPass
from zuspec.synth.passes.fsm_to_python import FSMToPythonPass
from zuspec.synth.passes.comb_to_python import CombToPythonPass
from zuspec.synth.passes.module_assemble_python import ModuleAssemblePythonPass
from zuspec.synth.ir.synth_ir import SynthIR, SynthConfig


def _build_ir(component_cls):
    ctx = DataModelFactory().build(component_cls)
    ir = SynthIR(component=component_cls, model_context=ctx)
    cfg = SynthConfig()
    ir = ComponentFieldsPass(cfg).run(ir)
    ir = ProcessToFSMPass(cfg).run(ir)
    ir = FSMToPythonPass(cfg).run(ir)
    ir = CombToPythonPass(cfg).run(ir)
    ir = ModuleAssemblePythonPass(cfg).run(ir)
    return ir


# ---------------------------------------------------------------------------
# Single-state assembly (blinky)
# ---------------------------------------------------------------------------

class TestModuleAssembleSingleState:
    @pytest.fixture(scope="class")
    def ir(self):
        import blink as spl_blink
        return _build_ir(spl_blink.Blink)

    def test_top_key_set(self, ir):
        assert "py/module/top" in ir.lowered_py

    def test_top_not_empty(self, ir):
        assert ir.lowered_py["py/module/top"]

    def test_has_class(self, ir):
        src = ir.lowered_py["py/module/top"]
        assert "class Blink" in src

    def test_has_decorator(self, ir):
        src = ir.lowered_py["py/module/top"]
        assert "@zdc.dataclass" in src

    def test_has_sync_method(self, ir):
        src = ir.lowered_py["py/module/top"]
        assert "@zdc.sync" in src

    def test_has_comb_method(self, ir):
        src = ir.lowered_py["py/module/top"]
        assert "@zdc.comb" in src

    def test_has_import(self, ir):
        src = ir.lowered_py["py/module/top"]
        assert "import zuspec.dataclasses as zdc" in src

    def test_has_ports(self, ir):
        src = ir.lowered_py["py/module/top"]
        assert "BTN_N" in src
        assert "LED_GREEN" in src
        assert "LED_RED" in src

    def test_has_state_var(self, ir):
        src = ir.lowered_py["py/module/top"]
        assert "_counter" in src

    def test_no_reset_none(self, ir):
        """reset=None should not appear in the output."""
        src = ir.lowered_py["py/module/top"]
        assert "reset=None" not in src

    def test_output_is_valid_python(self, ir):
        src = ir.lowered_py["py/module/top"]
        try:
            compile(src, "<generated>", "exec")
        except SyntaxError as exc:
            pytest.fail(f"Generated Python has syntax error: {exc}")


# ---------------------------------------------------------------------------
# Multi-state (rotate) — ModuleAssemblePythonPass should be a no-op
# ---------------------------------------------------------------------------

class TestModuleAssembleMultiState:
    @pytest.fixture(scope="class")
    def ir(self):
        import rotate as spl_rotate
        return _build_ir(spl_rotate.Blink)

    def test_top_key_set(self, ir):
        assert "py/module/top" in ir.lowered_py

    def test_multi_state_pass_is_noop(self, ir):
        """For multi-state, py/module/top was set by FSMToPythonPass; assembly should not change it."""
        src = ir.lowered_py["py/module/top"]
        # The FSMToPythonPass header identifies it
        assert "# Generated by zuspec-synth" in src
        # Should not have been double-assembled (e.g., no duplicate class decl)
        assert src.count("class Blink") == 1

    def test_output_is_valid_python(self, ir):
        src = ir.lowered_py["py/module/top"]
        try:
            compile(src, "<generated>", "exec")
        except SyntaxError as exc:
            pytest.fail(f"Generated Python has syntax error: {exc}")
