#****************************************************************************
# Copyright 2019-2026 Matthew Ballance and contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#****************************************************************************
"""Register file hazard analysis and SystemVerilog generation.

This module contains two main classes:

``RegFileHazardAnalyzer``
    Analyses pairs of concurrent ``IndexedRegFile`` accesses from the action
    DAG and determines which hardware structures (forwarding muxes, stall
    comparators) are required.

``RegFileSVGenerator``
    Generates a synthesisable SystemVerilog register file module from a
    ``RegFileDeclIR`` and the hazard analysis results.

Three RTL topologies are supported:

* **2R/1W separate** (``read_ports=2, shared_port=False``)  
  Two independent read port groups, one write port group.  RAW forwarding
  muxes are generated inside the module.

* **SDP — simple dual-port** (``read_ports=1, shared_port=False``)  
  One read port group, one write port group, both independent.  A single
  RAW forwarding mux is generated.

* **1P — true single-port** (``shared_port=True``)  
  One shared address/data bus.  Reads and writes are mutually exclusive;
  no in-module forwarding.  The pipeline controller (generated by the MLS
  scheduler) inserts stall cycles.

Design notes
------------
``idx`` values on concurrent claims are constrained-random variables whose
values are determined by the instruction decoder, not at elaboration time.
The analyser therefore conservatively assumes any two concurrent ``idx``
values *could* be equal unless a ``proven_distinct`` hint proves otherwise.
This conservative assumption drives comparator generation.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from textwrap import dedent, indent
from typing import FrozenSet, List, Optional, Set, Tuple

from ..elab.elab_ir import RegFileDeclIR


def _pfx(prefix: str, name: str) -> str:
    """Return '{prefix}_{name}' when prefix is non-empty, else '{name}'."""
    return f'{prefix}_{name}' if prefix else name


# ---------------------------------------------------------------------------
# Hazard data structures
# ---------------------------------------------------------------------------

@dataclass
class RegFileHazardPair:
    """Describes a hazard between two concurrent register file accesses.

    Attributes
    ----------
    kind:
        ``'RAW'`` — a write (producer) and a later read (consumer) could
                    alias; requires forwarding or stall.
        ``'WAW'`` — two concurrent writes could alias; requires suppression
                    or stall.
    writer_port:
        Index of the write port group (0-based) that produces the value.
    reader_port:
        Index of the read port group that consumes the value (RAW only;
        ``-1`` for WAW).
    comparator:
        ``True``  → a runtime ``(wp_addr == rp_addr)`` comparator is needed
                    inside the register file module.
        ``False`` → structural exclusion (``shared_port=True``) makes an
                    in-module comparator unnecessary; the pipeline controller
                    stalls instead.
    resolution:
        ``'forward'`` — insert a forwarding mux inside the module.
        ``'stall'``   — the pipeline controller must stall; no mux needed.
    """
    kind:         str   # 'RAW' | 'WAW'
    writer_port:  int
    reader_port:  int   # -1 for WAW
    comparator:   bool
    resolution:   str   # 'forward' | 'stall'


# ---------------------------------------------------------------------------
# Hazard analyser
# ---------------------------------------------------------------------------

class RegFileHazardAnalyzer:
    """Determines which hazard-detection structures are needed.

    Rules
    -----
    ``shared_port=False`` (separate physical buses):

    * ``(read, write)`` pair with potentially-equal ``idx``
      → RAW hazard, ``comparator=True``, ``resolution='forward'``
    * ``(write, write)`` pair with potentially-equal ``idx``
      → WAW hazard, ``comparator=True``, ``resolution='stall'``
    * ``(read, read)`` pair
      → no hazard

    ``shared_port=True`` (single shared bus):

    * Structural mutual exclusion prevents any same-cycle overlap.
      No in-module comparators are needed; the pipeline controller
      handles all hazard resolution via stall logic.
      → empty hazard list returned.

    Parameters to ``analyze``
    -------------------------
    decl:
        ``RegFileDeclIR`` describing the register file configuration.
    concurrent_read_ports:
        Number of read-port claims that can be in flight simultaneously.
        Typically ``decl.read_ports``.
    concurrent_write_ports:
        Number of write-port claims that can be in flight simultaneously.
        Typically ``decl.write_ports``.
    proven_distinct:
        Set of ``(read_port_idx, write_port_idx)`` pairs for which the
        constraint system has *proven* the corresponding ``idx`` values
        cannot be equal.  These pairs do not need a comparator.
    """

    def analyze(
            self,
            decl: RegFileDeclIR,
            concurrent_read_ports:  int = 0,
            concurrent_write_ports: int = 0,
            proven_distinct: FrozenSet[Tuple[int, int]] = frozenset(),
    ) -> List[RegFileHazardPair]:
        """Return the list of hazard pairs that require hardware support."""

        if decl.shared_port:
            # Structural exclusion — no in-module comparators needed.
            return []

        pairs: List[RegFileHazardPair] = []
        n_rp = concurrent_read_ports  or decl.read_ports
        n_wp = concurrent_write_ports or decl.write_ports

        # RAW: each (read_port, write_port) pair
        for rp in range(n_rp):
            for wp in range(n_wp):
                if (rp, wp) in proven_distinct:
                    continue   # constraint proves no aliasing — omit comparator
                pairs.append(RegFileHazardPair(
                    kind='RAW',
                    writer_port=wp,
                    reader_port=rp,
                    comparator=True,
                    resolution='forward',
                ))

        # WAW: each pair of write ports (only if more than one write port)
        for wp_a in range(n_wp):
            for wp_b in range(wp_a + 1, n_wp):
                pairs.append(RegFileHazardPair(
                    kind='WAW',
                    writer_port=wp_a,
                    reader_port=-1,
                    comparator=True,
                    resolution='stall',
                ))

        return pairs


# ---------------------------------------------------------------------------
# SystemVerilog generator
# ---------------------------------------------------------------------------

class RegFileSVGenerator:
    """Generates a synthesisable SystemVerilog register file module.

    Call :meth:`generate` with a ``RegFileDeclIR`` and the hazard analysis
    results to obtain the complete module source as a string.

    The generated module follows this port naming convention:

    Read ports (0 to ``read_ports-1``)::

        input  [IDX_W-1:0]  rp{N}_addr
        output [DATA_W-1:0] rp{N}_data

    Write ports (0 to ``write_ports-1``)::

        input  [IDX_W-1:0]  wp{N}_addr
        input  [DATA_W-1:0] wp{N}_data
        input               wp{N}_we

    Single-port (``shared_port=True``) replaces all of the above with::

        input  [IDX_W-1:0]  port_addr
        input  [DATA_W-1:0] port_wdata
        input               port_we
        output [DATA_W-1:0] port_rdata   // registered: 1-cycle read latency
    """

    def generate(self, decl: RegFileDeclIR,
                 hazards: Optional[List[RegFileHazardPair]] = None,
                 module_prefix: str = "") -> str:
        """Return the complete SV module source for *decl*."""
        if hazards is None:
            hazards = []

        if decl.shared_port:
            return self._gen_single_port(decl, module_prefix=module_prefix)
        elif decl.read_ports == 1:
            return self._gen_sdp(decl, hazards, module_prefix=module_prefix)
        else:
            return self._gen_multi_read(decl, hazards, module_prefix=module_prefix)

    # ------------------------------------------------------------------
    # Internal generators
    # ------------------------------------------------------------------

    def _module_name(self, decl: RegFileDeclIR, module_prefix: str = "") -> str:
        base = (
            f'{decl.field_name}_1p'   if decl.shared_port else
            f'{decl.field_name}_sdp'  if decl.read_ports == 1 else
            f'{decl.field_name}_{decl.read_ports}r{decl.write_ports}w'
        )
        return _pfx(module_prefix, base)

    def _gen_multi_read(self, decl: RegFileDeclIR,
                        hazards: List[RegFileHazardPair],
                        module_prefix: str = "") -> str:
        aw   = decl.idx_width
        dw   = decl.data_width
        dep  = decl.depth
        name = self._module_name(decl, module_prefix)

        lines: List[str] = []
        lines.append(f'// {decl.read_ports}R/{decl.write_ports}W register file')
        lines.append(f'// Separate read and write buses; RAW forwarding muxes generated.')
        lines.append(f'module {name} #(')
        lines.append(f'    parameter DEPTH     = {dep},')
        lines.append(f'    parameter IDX_WIDTH = {aw},')
        lines.append(f'    parameter DATA_WIDTH = {dw}')
        lines.append( ') (')
        lines.append( '    input  wire                   clk,')

        for rp in range(decl.read_ports):
            lines.append(f'    input  wire [IDX_WIDTH-1:0]   rp{rp}_addr,')
            lines.append(f'    output wire [DATA_WIDTH-1:0]  rp{rp}_data,')

        for wp in range(decl.write_ports):
            lines.append(f'    input  wire [IDX_WIDTH-1:0]   wp{wp}_addr,')
            lines.append(f'    input  wire [DATA_WIDTH-1:0]  wp{wp}_data,')
            last = (wp == decl.write_ports - 1)
            lines.append(f'    input  wire                   wp{wp}_we{"" if last else ","}')

        lines.append(');')
        lines.append(f'    // Register storage (regs[0] == x0 always reads as 0)')
        lines.append(f'    reg [DATA_WIDTH-1:0] regs [1:{dep-1}];')
        lines.append('')

        # RAW hazard comparators and forwarding muxes
        raw_hazards = [h for h in hazards if h.kind == 'RAW']
        if raw_hazards:
            lines.append('    // RAW hazard comparators')
            lines.append('    // idx is a rand variable: MLS conservatively generates a comparator')
            lines.append('    // for every concurrent (read_port, write_port) pair.')
            for h in raw_hazards:
                rp, wp = h.reader_port, h.writer_port
                lines.append(f'    wire raw_rp{rp}_wp{wp} = wp{wp}_we && (wp{wp}_addr == rp{rp}_addr);')
            lines.append('')

        # Read output assignments with forwarding mux
        lines.append('    // Read outputs with forwarding mux (write-through)')
        for rp in range(decl.read_ports):
            raw_for_rp = [h for h in raw_hazards if h.reader_port == rp]
            if raw_for_rp:
                # Build a chain of ternary muxes: last write wins
                expr = f'regs[rp{rp}_addr]'
                for h in raw_for_rp:
                    wp = h.writer_port
                    expr = f'(raw_rp{rp}_wp{wp} ? wp{wp}_data : {expr})'
                lines.append(f'    assign rp{rp}_data = (rp{rp}_addr == {aw}\'d0) ? {dw}\'d0 : {expr};')
            else:
                lines.append(f'    assign rp{rp}_data = (rp{rp}_addr == {aw}\'d0) ? {dw}\'d0 : regs[rp{rp}_addr];')
        lines.append('')

        # Write logic
        lines.append('    // Synchronous write (ignore writes to x0)')
        lines.append('    always @(posedge clk) begin')
        for wp in range(decl.write_ports):
            lines.append(f'        if (wp{wp}_we && wp{wp}_addr != {aw}\'d0)')
            lines.append(f'            regs[wp{wp}_addr] <= wp{wp}_data;')
        lines.append('    end')
        lines.append('endmodule')

        return '\n'.join(lines)

    def _gen_sdp(self, decl: RegFileDeclIR,
                 hazards: List[RegFileHazardPair],
                 module_prefix: str = "") -> str:
        """Simple dual-port: one read port, one write port, separate buses."""
        aw   = decl.idx_width
        dw   = decl.data_width
        dep  = decl.depth
        name = self._module_name(decl, module_prefix)

        lines: List[str] = []
        lines.append(f'// Simple dual-port register file (1R / 1W separate buses)')
        lines.append(f'// Maps to Xilinx BRAM simple-dual-port mode.')
        lines.append(f'module {name} #(')
        lines.append(f'    parameter DEPTH      = {dep},')
        lines.append(f'    parameter IDX_WIDTH  = {aw},')
        lines.append(f'    parameter DATA_WIDTH = {dw}')
        lines.append( ') (')
        lines.append( '    input  wire                   clk,')
        lines.append( '    input  wire [IDX_WIDTH-1:0]   rp0_addr,')
        lines.append( '    output wire [DATA_WIDTH-1:0]  rp0_data,')
        lines.append( '    input  wire [IDX_WIDTH-1:0]   wp0_addr,')
        lines.append( '    input  wire [DATA_WIDTH-1:0]  wp0_data,')
        lines.append( '    input  wire                   wp0_we')
        lines.append( ');')
        lines.append(f'    reg [DATA_WIDTH-1:0] regs [1:{dep-1}];')
        lines.append('')

        raw_hazards = [h for h in hazards if h.kind == 'RAW']
        if raw_hazards:
            lines.append('    // RAW comparator')
            lines.append('    wire raw_rp0_wp0 = wp0_we && (wp0_addr == rp0_addr);')
            lines.append(f'    assign rp0_data = (rp0_addr == {aw}\'d0) ? {dw}\'d0 :')
            lines.append( '                       (raw_rp0_wp0 ? wp0_data : regs[rp0_addr]);')
        else:
            lines.append(f'    assign rp0_data = (rp0_addr == {aw}\'d0) ? {dw}\'d0 : regs[rp0_addr];')

        lines.append('')
        lines.append('    always @(posedge clk)')
        lines.append(f'        if (wp0_we && wp0_addr != {aw}\'d0)')
        lines.append( '            regs[wp0_addr] <= wp0_data;')
        lines.append('endmodule')

        return '\n'.join(lines)

    def _gen_single_port(self, decl: RegFileDeclIR, module_prefix: str = "") -> str:
        """True single-port: one shared address/data bus (BRAM SP mode)."""
        aw   = decl.idx_width
        dw   = decl.data_width
        dep  = decl.depth
        name = self._module_name(decl, module_prefix)

        lines: List[str] = []
        lines.append(f'// True single-port register file (shared R/W bus)')
        lines.append(f'// Maps to Xilinx BRAM single-port mode, Intel M20K single-port.')
        lines.append(f'// Reads and writes are mutually exclusive; no forwarding mux.')
        lines.append(f'// Pipeline controller (generated by MLS) inserts stall cycles.')
        lines.append(f'module {name} #(')
        lines.append(f'    parameter DEPTH      = {dep},')
        lines.append(f'    parameter IDX_WIDTH  = {aw},')
        lines.append(f'    parameter DATA_WIDTH = {dw}')
        lines.append( ') (')
        lines.append( '    input  wire                   clk,')
        lines.append( '    input  wire [IDX_WIDTH-1:0]   port_addr,')
        lines.append( '    input  wire [DATA_WIDTH-1:0]  port_wdata,')
        lines.append( '    input  wire                   port_we,')
        lines.append( '    output reg  [DATA_WIDTH-1:0]  port_rdata')
        lines.append( ');')
        lines.append(f'    reg [DATA_WIDTH-1:0] regs [1:{dep-1}];')
        lines.append('')
        lines.append('    // Mutually exclusive read/write — no forwarding mux needed.')
        lines.append('    // The pipeline controller ensures port_we and a read never')
        lines.append('    // assert in the same cycle.')
        lines.append('    always @(posedge clk) begin')
        lines.append(f'        if (port_we && port_addr != {aw}\'d0)')
        lines.append( '            regs[port_addr] <= port_wdata;')
        lines.append( '        else')
        lines.append(f'            port_rdata <= (port_addr == {aw}\'d0) ? {dw}\'d0 : regs[port_addr];')
        lines.append('    end')
        lines.append('endmodule')

        return '\n'.join(lines)
