#****************************************************************************
# Copyright 2019-2026 Matthew Ballance and contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#****************************************************************************
"""
SystemVerilog Code Generator: Generates synthesizable SV from FSM IR.

This module converts FSM IR to synthesizable SystemVerilog code following
best practices for FPGA and ASIC synthesis:
- Explicit state machine coding style
- Synchronous reset (or async reset with proper coding)
- Separate combinational and sequential logic
- Clean port declarations
"""

from typing import List, Dict, Set, Optional, Any, TextIO
from dataclasses import dataclass, field
from enum import Enum, auto
from io import StringIO

from .fsm_ir import (
    FSMModule, FSMState, FSMStateKind, FSMTransition,
    FSMOperation, FSMAssign, FSMCond, FSMPort, FSMRegister
)
from .fsm_generator import StateEncoding


class ResetStyle(Enum):
    """Reset coding styles."""
    ASYNC_LOW = auto()    # Asynchronous active-low reset (rst_n)
    ASYNC_HIGH = auto()   # Asynchronous active-high reset (rst)
    SYNC_LOW = auto()     # Synchronous active-low reset
    SYNC_HIGH = auto()    # Synchronous active-high reset


class FSMStyle(Enum):
    """FSM coding styles."""
    ONE_PROCESS = auto()      # Single always_ff block
    TWO_PROCESS = auto()      # Separate comb and seq blocks
    THREE_PROCESS = auto()    # State reg, next state logic, output logic


@dataclass
class SVGenConfig:
    """Configuration for SystemVerilog generation.
    
    Attributes:
        reset_style: Reset coding style
        fsm_style: FSM coding style
        use_logic: Use 'logic' instead of 'reg/wire'
        use_always_ff: Use always_ff/always_comb (SV) vs always (Verilog)
        indent: Indentation string
        generate_comments: Include comments in output
        state_type_name: Name for state enum type
    """
    reset_style: ResetStyle = ResetStyle.ASYNC_LOW
    fsm_style: FSMStyle = FSMStyle.TWO_PROCESS
    use_logic: bool = True
    use_always_ff: bool = True
    indent: str = "  "
    generate_comments: bool = True
    state_type_name: str = "state_t"


class SVCodeGenerator:
    """Generates SystemVerilog code from FSM IR.
    
    Usage:
        generator = SVCodeGenerator()
        sv_code = generator.generate(fsm_module)
    """
    
    def __init__(self, config: Optional[SVGenConfig] = None):
        """Initialize the code generator.
        
        Args:
            config: Generation configuration
        """
        self.config = config or SVGenConfig()
        self._indent_level = 0
        self._output: StringIO = StringIO()
    
    def generate(self, fsm: FSMModule) -> str:
        """Generate SystemVerilog code for an FSM module.
        
        Args:
            fsm: FSM module to generate code for
            
        Returns:
            SystemVerilog source code as string
        """
        self._output = StringIO()
        self._indent_level = 0
        
        self._generate_header(fsm)
        self._generate_user_enum_typedefs(fsm)
        self._generate_module_declaration(fsm)
        self._generate_state_encoding(fsm)
        self._generate_register_declarations(fsm)
        self._generate_state_register(fsm)
        self._generate_next_state_logic(fsm)
        self._generate_output_logic(fsm)
        self._generate_module_end()
        
        return self._output.getvalue()
    
    def _emit(self, text: str = ""):
        """Emit text to output."""
        self._output.write(text)
    
    def _emitln(self, text: str = ""):
        """Emit text with newline."""
        self._emit(self._get_indent() + text + "\n")
    
    def _get_indent(self) -> str:
        """Get current indentation string."""
        return self.config.indent * self._indent_level
    
    def _indent(self):
        """Increase indentation."""
        self._indent_level += 1
    
    def _dedent(self):
        """Decrease indentation."""
        self._indent_level = max(0, self._indent_level - 1)
    
    def _generate_header(self, fsm: FSMModule):
        """Generate file header comment."""
        if self.config.generate_comments:
            self._emitln("//")
            self._emitln(f"// Module: {fsm.name}")
            self._emitln("// Generated by zuspec-synth SPRTL compiler")
            self._emitln("//")
            self._emitln()

    def _generate_user_enum_typedefs(self, fsm: FSMModule):
        """Emit ``typedef enum logic`` declarations for user-defined enums.

        One typedef is emitted per entry in ``fsm.user_enums``.  These are
        emitted *before* the module declaration so they can be used as port
        or register types within the module.
        """
        if not fsm.user_enums:
            return
        if self.config.generate_comments:
            self._emitln("// User-defined enum types")
        for enum_info in fsm.user_enums:
            name = enum_info['name']
            width = enum_info['width']
            items = enum_info['items']
            self._emitln(f"typedef enum logic [{width - 1}:0] {{")
            self._indent()
            item_list = list(items.items())
            for i, (member, value) in enumerate(item_list):
                comma = "," if i < len(item_list) - 1 else ""
                self._emitln(f"{member} = {width}'d{value}{comma}")
            self._dedent()
            self._emitln(f"}} {name}_t;")
            self._emitln()

    def _generate_module_declaration(self, fsm: FSMModule):
        """Generate module declaration with ports."""
        self._emitln(f"module {fsm.name} (")
        self._indent()
        
        # Clock and reset first
        self._emitln(f"input  logic {fsm.clock_signal},")
        self._emitln(f"input  logic {fsm.reset_signal},")
        
        # Other ports
        ports = [p for p in fsm.ports 
                if p.name not in (fsm.clock_signal, fsm.reset_signal)]
        
        for i, port in enumerate(ports):
            direction = "input " if port.direction == "input" else "output"
            width_str = self._format_width(port.width)
            comma = "," if i < len(ports) - 1 else ""
            self._emitln(f"{direction} logic {width_str}{port.name}{comma}")
        
        self._dedent()
        self._emitln(");")
        self._emitln()
    
    def _format_width(self, width: int) -> str:
        """Format port/signal width declaration."""
        if width == 1:
            return ""
        return f"[{width-1}:0] "
    
    def _generate_state_encoding(self, fsm: FSMModule):
        """Generate state type and encoding."""
        if not fsm.states:
            return
        
        if self.config.generate_comments:
            self._emitln("// State encoding")
        
        # Generate enum type
        width = fsm.state_width or 1
        self._emitln(f"typedef enum logic [{width-1}:0] {{")
        self._indent()
        
        for i, state in enumerate(fsm.states):
            encoded = fsm.state_encoding.get(state.id, i)
            comma = "," if i < len(fsm.states) - 1 else ""
            self._emitln(f"{state.name} = {width}'d{encoded}{comma}")
        
        self._dedent()
        self._emitln(f"}} {self.config.state_type_name};")
        self._emitln()
        
        # State registers
        self._emitln(f"{self.config.state_type_name} state, next_state;")
        self._emitln()
    
    def _generate_register_declarations(self, fsm: FSMModule):
        """Generate internal register declarations."""
        if not fsm.registers:
            return
        
        # Filter out state register (already declared)
        regs = [r for r in fsm.registers if r.name != "state"]
        if not regs:
            return
        
        if self.config.generate_comments:
            self._emitln("// Internal registers")
        
        for reg in regs:
            width_str = self._format_width(reg.width)
            self._emitln(f"logic {width_str}{reg.name};")
        
        self._emitln()
    
    def _generate_state_register(self, fsm: FSMModule):
        """Generate state register with reset."""
        if not fsm.states:
            return
        
        if self.config.generate_comments:
            self._emitln("// State register")
        
        initial_state = fsm.get_state(fsm.initial_state)
        initial_name = initial_state.name if initial_state else "IDLE"
        
        if self.config.reset_style == ResetStyle.ASYNC_LOW:
            self._emitln(f"always_ff @(posedge {fsm.clock_signal} or negedge {fsm.reset_signal}) begin")
            self._indent()
            self._emitln(f"if (!{fsm.reset_signal})")
            self._indent()
            self._emitln(f"state <= {initial_name};")
            self._dedent()
            self._emitln("else")
            self._indent()
            self._emitln("state <= next_state;")
            self._dedent()
            self._dedent()
            self._emitln("end")
        elif self.config.reset_style == ResetStyle.SYNC_LOW:
            self._emitln(f"always_ff @(posedge {fsm.clock_signal}) begin")
            self._indent()
            self._emitln(f"if (!{fsm.reset_signal})")
            self._indent()
            self._emitln(f"state <= {initial_name};")
            self._dedent()
            self._emitln("else")
            self._indent()
            self._emitln("state <= next_state;")
            self._dedent()
            self._dedent()
            self._emitln("end")
        
        self._emitln()
    
    def _generate_next_state_logic(self, fsm: FSMModule):
        """Generate combinational next state logic."""
        if not fsm.states:
            return
        
        if self.config.generate_comments:
            self._emitln("// Next state logic")
        
        self._emitln("always_comb begin")
        self._indent()
        self._emitln("next_state = state;")
        self._emitln("case (state)")
        self._indent()
        
        for state in fsm.states:
            self._emitln(f"{state.name}: begin")
            self._indent()
            
            # Generate transitions
            if state.transitions:
                # Handle conditional and unconditional transitions
                conditional = [t for t in state.transitions if t.condition is not None]
                unconditional = [t for t in state.transitions if t.condition is None]
                
                for trans in conditional:
                    target = fsm.get_state(trans.target_state)
                    target_name = target.name if target else f"S{trans.target_state}"
                    cond_str = self._format_condition(trans.condition)
                    self._emitln(f"if ({cond_str})")
                    self._indent()
                    self._emitln(f"next_state = {target_name};")
                    self._dedent()
                
                if unconditional:
                    target = fsm.get_state(unconditional[0].target_state)
                    target_name = target.name if target else f"S{unconditional[0].target_state}"
                    if conditional:
                        self._emitln("else")
                        self._indent()
                        self._emitln(f"next_state = {target_name};")
                        self._dedent()
                    else:
                        self._emitln(f"next_state = {target_name};")
            
            self._dedent()
            self._emitln("end")
        
        self._emitln("default: next_state = state;")
        self._dedent()
        self._emitln("endcase")
        self._dedent()
        self._emitln("end")
        self._emitln()
    
    def _format_condition(self, condition: Any) -> str:
        """Format a condition expression as SystemVerilog."""
        if condition is None:
            return "1'b1"
        
        # Handle different condition types
        if hasattr(condition, 'left') and hasattr(condition, 'op') and hasattr(condition, 'right'):
            # Binary comparison
            left = self._format_expr(condition.left)
            right = self._format_expr(condition.right)
            op = self._format_operator(condition.op)
            return f"{left} {op} {right}"
        
        # Simple expression
        return self._format_expr(condition)
    
    def _format_expr(self, expr: Any) -> str:
        """Format an expression as SystemVerilog."""
        if expr is None:
            return "0"
        
        if isinstance(expr, (int, float)):
            return str(expr)
        
        if isinstance(expr, str):
            return expr
        
        if hasattr(expr, 'name'):
            return expr.name
        
        if hasattr(expr, 'attr'):
            return expr.attr
        
        if hasattr(expr, 'value'):
            return str(expr.value)
        
        return str(expr)
    
    def _format_operator(self, op: Any) -> str:
        """Format an operator."""
        op_map = {
            'Eq': '==',
            'NotEq': '!=',
            'Lt': '<',
            'LtE': '<=',
            'Gt': '>',
            'GtE': '>=',
            'Add': '+',
            'Sub': '-',
            'Mult': '*',
            'Div': '/',
            'Mod': '%',
            'BitAnd': '&',
            'BitOr': '|',
            'BitXor': '^',
            'And': '&&',
            'Or': '||',
        }
        
        if hasattr(op, 'name'):
            return op_map.get(op.name, str(op.name))
        
        return op_map.get(str(op), str(op))
    
    def _generate_output_logic(self, fsm: FSMModule):
        """Generate output/datapath logic."""
        # Collect all operations from states
        has_operations = any(state.operations for state in fsm.states)
        if not has_operations:
            return
        
        if self.config.generate_comments:
            self._emitln("// Output and datapath logic")
        
        # Get output ports for reset
        output_ports = fsm.get_output_ports()
        
        if self.config.reset_style == ResetStyle.ASYNC_LOW:
            self._emitln(f"always_ff @(posedge {fsm.clock_signal} or negedge {fsm.reset_signal}) begin")
            self._indent()
            self._emitln(f"if (!{fsm.reset_signal}) begin")
            self._indent()
            
            # Reset assignments for outputs
            for port in output_ports:
                reset_val = self._format_reset_value(port.reset_value, port.width)
                self._emitln(f"{port.name} <= {reset_val};")
            
            # Reset internal registers
            for reg in fsm.registers:
                if reg.name != "state":
                    reset_val = self._format_reset_value(reg.reset_value, reg.width)
                    self._emitln(f"{reg.name} <= {reset_val};")
            
            self._dedent()
            self._emitln("end else begin")
            self._indent()
            self._emitln("case (state)")
            self._indent()
            
            for state in fsm.states:
                if state.operations:
                    self._emitln(f"{state.name}: begin")
                    self._indent()
                    self._generate_operations(state.operations)
                    self._dedent()
                    self._emitln("end")
            
            self._emitln("default: ; // No operation")
            self._dedent()
            self._emitln("endcase")
            self._dedent()
            self._emitln("end")
            self._dedent()
            self._emitln("end")
        
        self._emitln()
    
    def _format_reset_value(self, value: Any, width: int) -> str:
        """Format a reset value."""
        if value is None:
            return f"{width}'d0"
        if isinstance(value, int):
            return f"{width}'d{value}"
        return str(value)
    
    def _generate_operations(self, operations: List[FSMOperation]):
        """Generate code for a list of operations."""
        for op in operations:
            if isinstance(op, FSMAssign):
                self._generate_assign(op)
            elif isinstance(op, FSMCond):
                self._generate_conditional(op)
    
    def _generate_assign(self, op: FSMAssign):
        """Generate assignment statement."""
        target = op.target
        value = self._format_assign_value(op.value)
        
        if op.is_nonblocking:
            self._emitln(f"{target} <= {value};")
        else:
            self._emitln(f"{target} = {value};")
    
    def _format_assign_value(self, value: Any) -> str:
        """Format the RHS of an assignment."""
        if value is None:
            return "0"
        
        if isinstance(value, (int, float)):
            return str(value)
        
        if isinstance(value, str):
            return value
        
        if isinstance(value, tuple) and len(value) == 3:
            # Augmented assignment: (target, op, value)
            target, op, rhs = value
            target_str = self._format_expr(target)
            rhs_str = self._format_expr(rhs)
            op_str = self._format_operator(op)
            return f"{target_str} {op_str} {rhs_str}"
        
        return self._format_expr(value)
    
    def _generate_conditional(self, op: FSMCond):
        """Generate conditional (if/else) statement."""
        cond_str = self._format_condition(op.condition)
        
        self._emitln(f"if ({cond_str}) begin")
        self._indent()
        self._generate_operations(op.then_ops)
        self._dedent()
        
        if op.else_ops:
            self._emitln("end else begin")
            self._indent()
            self._generate_operations(op.else_ops)
            self._dedent()
        
        self._emitln("end")
    
    def _generate_module_end(self):
        """Generate module end."""
        self._emitln("endmodule")


def generate_sv(fsm: FSMModule, config: Optional[SVGenConfig] = None) -> str:
    """Convenience function to generate SystemVerilog code.
    
    When ``config`` is ``None``, the reset style is auto-derived from
    ``fsm.reset_async`` and ``fsm.reset_active_low``:

    ==============================  ==================
    fsm fields                      Derived reset_style
    ==============================  ==================
    reset_async=True,  active_low   ASYNC_LOW
    reset_async=True,  active_high  ASYNC_HIGH
    reset_async=False, active_low   SYNC_LOW
    reset_async=False, active_high  SYNC_HIGH
    ==============================  ==================

    Args:
        fsm: FSM module to generate
        config: Optional generation configuration; overrides auto-derivation.
        
    Returns:
        SystemVerilog source code
    """
    if config is None:
        if fsm.reset_async and fsm.reset_active_low:
            reset_style = ResetStyle.ASYNC_LOW
        elif fsm.reset_async and not fsm.reset_active_low:
            reset_style = ResetStyle.ASYNC_HIGH
        elif not fsm.reset_async and fsm.reset_active_low:
            reset_style = ResetStyle.SYNC_LOW
        else:
            reset_style = ResetStyle.SYNC_HIGH
        config = SVGenConfig(reset_style=reset_style)
    generator = SVCodeGenerator(config)
    return generator.generate(fsm)


def generate_regfile_sv(meta, module_prefix: str = "") -> str:
    """Generate SystemVerilog for all IndexedRegFile fields in *meta*.

    Args:
        meta: ``ComponentSynthMeta`` instance (from the elaborator).
        module_prefix: Optional prefix string applied to all generated module names.

    Returns:
        Concatenated SV source for every register file declared in the
        component, separated by blank lines.  Returns an empty string if
        the component has no ``IndexedRegFile`` fields.
    """
    from .regfile_synth import RegFileHazardAnalyzer, RegFileSVGenerator

    analyzer  = RegFileHazardAnalyzer()
    generator = RegFileSVGenerator()
    parts = []

    for decl in meta.regfiles:
        hazards = analyzer.analyze(decl)
        sv      = generator.generate(decl, hazards, module_prefix=module_prefix)
        parts.append(sv)

    return '\n\n'.join(parts)
