"""
Pipeline intermediate representation produced by the Lowerer pass.

``PipelineIR`` is the central data structure for Phase 2+.  It describes a
multi-stage pipeline as a list of named ``StageIR`` nodes connected by
``ChannelDecl`` (register) edges.

Extended for ``@zdc.pipeline`` support:
- ``ForwardingDecl`` — a per-signal forwarding (bypass) or stall declaration.
- ``HazardPair`` — a detected RAW/WAW/WAR hazard between two stages.
- ``RegFileAccess`` — a detected ``self.FIELD.read(addr)`` or ``.write(idx, val)`` call.
- ``RegFileHazard`` — a RAW hazard between a regfile write and a later read.
- ``StageIR.operations`` — AST operation nodes belonging to this stage.
- ``PipelineIR.forwarding`` / ``hazards`` — populated by the analysis passes.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from ..elab.elab_ir import ComponentSynthMeta, PortDecl


@dataclass
class ChannelDecl:
    """An inter-stage pipeline register carrying a live variable across a boundary."""
    name: str        # e.g. "a_if_to_ex"
    width: int       # total data width in bits (e.g. 32 for u32)
    depth: int       # register depth (always 1 for pipeline registers)
    src_stage: str   # name of the producing StageIR (e.g. "IF")
    dst_stage: str   # name of the consuming StageIR (e.g. "EX")


@dataclass
class ForwardingDecl:
    """A forwarding (bypass) or no-forward (stall) declaration between two stages.

    Created from ``zdc.forward(from_stage=X, to_stage=Y, var=v)`` /
    ``zdc.no_forward(...)`` calls in the process body, or auto-generated by
    ``ForwardingGenPass`` when ``forward_default`` is ``True`` or ``False``.
    """
    from_stage: str          # producer stage name (e.g. "EX")
    to_stage:   str          # consumer stage name (e.g. "ID")
    signal:     str          # variable name being forwarded/stalled
    suppressed: bool = False # True → no_forward (stall); False → forward (bypass mux)


@dataclass
class HazardPair:
    """A detected data hazard between two pipeline stages.

    Populated by ``HazardAnalysisPass``; resolution filled in by
    ``ForwardingGenPass``.
    """
    kind:           str  # "RAW", "WAR", or "WAW"
    producer_stage: str
    consumer_stage: str
    signal:         str
    resolved_by:    str = "unresolved"  # "forward", "stall", or "unresolved"


@dataclass
class RegFileDeclInfo:
    """Describes an ``IndexedRegFile`` or ``PipelineResource`` field used in the pipeline body.

    Built by :class:`~zuspec.synth.passes.hazard_analysis.HazardAnalysisPass`
    from the accesses found in the stage AST bodies.

    Attributes
    ----------
    field_name:
        Component field name, e.g. ``"regfile"``.
    depth:
        Number of entries (e.g. 32 for a 32-entry RISC-V integer regfile).
    addr_width:
        Address bit-width (typically ``ceil(log2(depth))``).
    data_width:
        Data bit-width (e.g. 32).
    lock_type:
        Hazard resolution strategy: ``"bypass"`` (forwarding mux) or
        ``"queue"`` (stall until write completes).  Defaults to ``"bypass"``
        which matches the ``BypassLock`` / ``forward_default=True`` behaviour.
    """
    field_name:  str
    depth:       int = 32
    addr_width:  int = 5
    data_width:  int = 32
    lock_type:   str = "bypass"  # "bypass" or "queue"


@dataclass
class RegFileAccess:
    """A single ``IndexedRegFile`` read or write detected in a pipeline stage body.

    Populated by ``HazardAnalysisPass`` during AST scanning.

    Attributes
    ----------
    field_name:
        Name of the component field (e.g. ``"regfile"``).
    kind:
        ``"read"`` or ``"write"``.
    stage:
        Name of the pipeline stage containing this access.
    addr_var:
        Name of the address variable (e.g. ``"rs1"`` or ``"rd"``).
    data_var:
        For writes, the data variable name (e.g. ``"result"``).
        Empty for reads.
    result_var:
        For reads, the variable the read result is assigned to (e.g. ``"rdata1"``).
        Empty for writes.
    data_width:
        Data width in bits (default 32).
    addr_width:
        Address width in bits (default 5 for 32-entry regfile).
    """
    field_name:  str
    kind:        str   # "read" or "write"
    stage:       str
    addr_var:    str
    data_var:    str = ""
    result_var:  str = ""
    data_width:  int = 32
    addr_width:  int = 5


@dataclass
class RegFileHazard:
    """A RAW hazard between an ``IndexedRegFile`` write and a later read.

    Detected by ``HazardAnalysisPass`` and resolved by ``ForwardingGenPass``.

    Attributes
    ----------
    field_name:
        Component field name (e.g. ``"regfile"``).
    write_stage:
        Name of the stage performing the write.
    read_stage:
        Name of the stage performing the read.
    write_addr_var:
        Address variable for the write (e.g. ``"rd"``).
    read_addr_var:
        Address variable for the read (e.g. ``"rs1"``).
    write_data_var:
        Data variable being written (e.g. ``"result"``).
    read_result_var:
        Variable receiving the read result (e.g. ``"rdata1"``).
    resolved_by:
        ``"forward"`` — comparator + mux bypass;
        ``"stall"``   — comparator drives stall signal;
        ``"unresolved"`` — not yet decided.
    suppressed:
        ``True`` when the user declared ``no_forward`` for this hazard.
    """
    field_name:      str
    write_stage:     str
    read_stage:      str
    write_addr_var:  str
    read_addr_var:   str
    write_data_var:  str
    read_result_var: str
    resolved_by:     str  = "unresolved"
    suppressed:      bool = False


@dataclass
class StageIR:
    """One pipeline stage."""
    name:       str
    index:      int
    inputs:     List[ChannelDecl] = field(default_factory=list)
    outputs:    List[ChannelDecl] = field(default_factory=list)
    ports:      List["PortDecl"]  = field(default_factory=list)
    operations: List[Any]         = field(default_factory=list)  # AST ops in this stage
    cycle_lo:   int = 0  # first clock cycle this stage occupies (for multi-cycle ops)
    cycle_hi:   int = 0  # last clock cycle this stage occupies (inclusive)
    # New-API fields (SY-1)
    no_forward:   bool     = False  # per-stage no-forward flag from @zdc.stage(no_forward=True)
    stall_cond:   Any      = None   # lowered AST for zdc.stage.stall(...) if present
    cancel_cond:  Any      = None   # lowered AST for zdc.stage.cancel(...) if present
    flush_decls:  List[Any] = field(default_factory=list)  # List[FlushDeclNode] from stage body


@dataclass
class SyncIR:
    """IR for one ``@zdc.sync``-decorated method, stored on PipelineIR.

    Populated by :class:`~zuspec.synth.passes.pipeline_frontend.PipelineFrontendPass`.
    Consumed by :class:`~zuspec.synth.passes.sync_body_lower.SyncBodyLowerPass` and
    the SV emitter.
    """
    name:        str
    clock:       Optional[str]   = None
    reset:       Optional[str]   = None
    flush_decls: List[Any]       = field(default_factory=list)  # FlushDeclNode list
    body_ast:    Any             = None  # ast.FunctionDef


@dataclass
class PipelineIR:
    """Lowered pipeline topology for a single component configuration.

    Both ``PipelineAnnotationPass`` (Approach C) and ``SDCSchedulePass``
    (Approach A) produce a ``PipelineIR``.  All downstream passes
    (``HazardAnalysisPass``, ``ForwardingGenPass``, ``StallGenPass``,
    ``SVEmitPass``, ``PipelineToSource``) operate on this representation and
    are unaware of which approach produced it.
    """
    module_name:          str
    stages:               List[StageIR]
    channels:             List[ChannelDecl]
    meta:                 Optional["ComponentSynthMeta"]
    pipeline_stages:      int
    forwarding:           List[ForwardingDecl]  = field(default_factory=list)
    hazards:              List[HazardPair]       = field(default_factory=list)
    regfile_accesses:     List[RegFileAccess]    = field(default_factory=list)
    regfile_hazards:      List[RegFileHazard]    = field(default_factory=list)
    regfile_decls:        List[RegFileDeclInfo]  = field(default_factory=list)
    initiation_interval:  int                    = 1
    approach:             str                    = "C"   # "A" or "C"
    source_annotation:    Optional[str]          = None  # PipelineToSource output (Approach A)
    forward_default:      Optional[bool]         = None  # process-level forward= value
    annotation_map:       Dict[str, Any]         = field(default_factory=dict)  # var → AST annotation node
    port_widths:          Dict[str, int]         = field(default_factory=dict)  # port_name → bit-width from component fields
    module_globals:       Dict[str, Any]         = field(default_factory=dict)  # module-level constants (e.g. ACCUM_MAX)
    # New-API fields (SY-1)
    sync_irs:    List[SyncIR]  = field(default_factory=list)  # @zdc.sync methods
    clock_field: Optional[str] = None   # component field name for clock
    reset_field: Optional[str] = None   # component field name for reset
    # Async-pipeline extension fields
    bubble_stages: List[str]   = field(default_factory=list)
    """Stage names that insert pipeline bubbles (derived from ``IrBubble`` nodes).

    When a stage appears in this list, ``SVEmitPass`` emits a
    ``{stage_lower}_bubble`` wire and gates the downstream stage's valid
    register on ``!{stage_lower}_bubble``.  ``StallGenPass`` uses this list
    to set the correct ``source_valid`` expression for the subsequent stage.
    """
    # Method port fields — populated by AsyncPipelineToIrPass from IrIngressOp/IrEgressOp.
    # Each entry is (port_name, width_bits).
    ingress_ports: List[tuple] = field(default_factory=list)
    """``[(port_name, width)]`` for each ``InPort.get()`` call detected."""
    egress_ports:  List[tuple] = field(default_factory=list)
    """``[(port_name, width)]`` for each ``OutPort.put()`` call detected."""
    clock_domain_field: Optional[str] = None
    """Component field name for the :class:`ClockDomain` (new clock_domain= form)."""
    ingress_var_map: Dict[str, str] = field(default_factory=dict)
    """Mapping from Python local variable name → ingress port name.

    Populated from ``IrIngressOp.result_var`` → ``IrIngressOp.port_name``.
    Used by :class:`~zuspec.synth.passes.expr_lowerer.ExprLowerer` to
    substitute ingress variable names with their port data signals.
    """

