# Copyright 2019-2026 Matthew Ballance and contributors
# SPDX-License-Identifier: Apache-2.0
"""ModuleAssemblePass — assemble SV fragments into a complete module."""
from __future__ import annotations

import logging

from .synth_pass import SynthPass
from zuspec.synth.ir.synth_ir import SynthIR

_log = logging.getLogger(__name__)

_HEADER = """\
// Generated by zuspec-synth
`timescale 1ns/1ps"""


class ModuleAssemblePass(SynthPass):
    """Assemble the header, port list, body fragments, and footer into final SV.

    Reads:
        ir.component_fields: Provides module_name and port declarations.
        ir.lowered_sv["sv/module/clocked"]: Clocked body text (always_ff).
        ir.lowered_sv["sv/module/comb"]: Combinational body text (always_comb).

    Populates:
        ir.lowered_sv["sv/module/top"]: The complete, self-contained SV source.
    """

    @property
    def name(self) -> str:
        return "module_assemble"

    def run(self, ir: SynthIR) -> SynthIR:
        # If FSMToRTLPass already produced a complete module (multi-state path),
        # the result is already in sv/module/top — nothing more to assemble.
        if "sv/module/top" in ir.lowered_sv:
            sv = ir.lowered_sv["sv/module/top"]
            _log.debug(
                "[ModuleAssemblePass] using pre-assembled module (%d chars)", len(sv)
            )
            return ir

        cf = ir.component_fields
        if cf is None:
            raise ValueError(
                "ModuleAssemblePass: ir.component_fields is None — "
                "run ComponentFieldsPass first."
            )

        module_name = cf.module_name or getattr(ir.component, "__name__", "module")

        # Build port list.
        port_lines: list[str] = []

        for p in cf.ports:
            w = _port_width_str(p)
            dir_kw = "output" if p.direction == "output" else "input "
            port_lines.append(f"  {dir_kw} logic {w}{p.name}")

        clocked_body = ir.lowered_sv.get("sv/module/clocked", "")
        comb_body = ir.lowered_sv.get("sv/module/comb", "")

        # Assemble.
        lines: list[str] = [_HEADER]
        lines.append(f"module {module_name} (")
        lines.append(",\n".join(port_lines))
        lines.append(");")
        lines.append("")

        if clocked_body:
            lines.append(clocked_body)

        if comb_body:
            if clocked_body and not clocked_body.endswith("\n\n"):
                lines.append("")
            lines.append(comb_body)

        lines.append("")
        lines.append("endmodule")

        result = "\n".join(lines) + "\n"
        ir.lowered_sv["sv/module/top"] = result
        _log.debug("[ModuleAssemblePass] assembled %d chars for %r", len(result), module_name)
        return ir


# ---------------------------------------------------------------------------
# Width helpers
# ---------------------------------------------------------------------------

def _port_width_str(p) -> str:
    width = getattr(p, "width", 1)
    if width <= 1:
        return ""
    return f"[{width - 1}:0] "
