# Copyright 2019-2026 Matthew Ballance and contributors
# SPDX-License-Identifier: Apache-2.0
"""ModuleAssemblePythonPass — assemble Python fragments into a complete class.

Place in pass chain
-------------------
Final pass in the Python backend chain.  Runs after ``CombToPythonPass``.

Inputs
------
- ``ir.component_fields`` — Provides module_name, ports, state_vars.
- ``ir.lowered_py["py/module/top"]``  — If already set (multi-state path),
  this pass is a no-op.
- ``ir.lowered_py["py/module/sync"]`` — ``@zdc.sync`` method text.
- ``ir.lowered_py["py/module/comb"]`` — ``@zdc.comb`` method text(s).
- ``ir.component``                    — For reset_domain.

Outputs
-------
- ``ir.lowered_py["py/module/top"]`` — Complete, standalone Python class.
"""
from __future__ import annotations

import logging

from .synth_pass import SynthPass
from zuspec.synth.ir.synth_ir import SynthIR

_log = logging.getLogger(__name__)

_HEADER = "# Generated by zuspec-synth — IR round-trip reconstruction"


class ModuleAssemblePythonPass(SynthPass):
    """Assemble ``@zdc.sync`` / ``@zdc.comb`` fragments into a full class.

    Multi-state path
        ``py/module/top`` already set by ``FSMToPythonPass``.  This pass
        is a no-op.

    Single-state path
        Build a class from:
        * Import header
        * ``@zdc.dataclass`` / ``class NAME(zdc.SyncComponent):``
        * ``reset_domain`` (if any)
        * Port declarations
        * State-variable declarations
        * ``@zdc.sync`` method body (from ``py/module/sync``)
        * ``@zdc.comb`` method body (from ``py/module/comb``, if present)
    """

    @property
    def name(self) -> str:
        return "module_assemble_python"

    def run(self, ir: SynthIR) -> SynthIR:
        if "py/module/top" in ir.lowered_py:
            src = ir.lowered_py["py/module/top"]
            _log.debug(
                "[ModuleAssemblePythonPass] using pre-assembled class (%d chars)",
                len(src),
            )
            return ir

        cf = ir.component_fields
        if cf is None:
            raise ValueError(
                "ModuleAssemblePythonPass: ir.component_fields is None — "
                "run ComponentFieldsPass first."
            )

        module_name = cf.module_name or getattr(ir.component, "__name__", "Module")

        lines: list[str] = [
            _HEADER,
            "import zuspec.dataclasses as zdc",
            "",
        ]

        # Class decorator + declaration
        lines.append("@zdc.dataclass")
        lines.append(f"class {module_name}(zdc.SyncComponent):")

        # reset_domain (propagate from original component)
        rd = (
            getattr(ir.component, "reset_domain", None)
            if ir.component
            else None
        )
        if rd is not None:
            rd_style = getattr(getattr(rd, "style", None), "value", None)
            if rd_style == "none":
                lines.append('    reset_domain = zdc.ResetDomain(style="none")')
                lines.append("")

        # Port declarations (skip injected clock/reset)
        lines.append("    # Ports")
        for p in cf.ports:
            if p.name in ("clk", "rst_n"):
                continue
            w = p.width
            type_ann = "zdc.bv" if w > 1 else "zdc.bit"
            if p.direction == "output":
                decl = f"zdc.output(width={w})" if w > 1 else "zdc.output()"
            else:
                decl = f"zdc.input(width={w})" if w > 1 else "zdc.input()"
            lines.append(f"    {p.name}: {type_ann} = {decl}")
        lines.append("")

        # State-variable (register) declarations
        if cf.state_vars:
            lines.append("    # State variables")
            for sv in cf.state_vars:
                w = getattr(sv, "width", 1)
                reset = getattr(sv, "reset_value", 0)
                name = sv.name
                if w > 1:
                    if reset is not None:
                        lines.append(
                            f"    {name}: zdc.bv = zdc.field(width={w}, reset={reset})"
                        )
                    else:
                        lines.append(
                            f"    {name}: zdc.bv = zdc.field(width={w})"
                        )
                else:
                    if reset is not None:
                        lines.append(
                            f"    {name}: zdc.bit = zdc.field(reset={reset})"
                        )
                    else:
                        lines.append(
                            f"    {name}: zdc.bit = zdc.field()"
                        )
            lines.append("")

        # @zdc.sync method
        sync_body = ir.lowered_py.get("py/module/sync", "")
        if sync_body:
            lines.extend(sync_body.splitlines())
            lines.append("")

        # @zdc.comb method(s)
        comb_body = ir.lowered_py.get("py/module/comb", "")
        if comb_body:
            lines.extend(comb_body.splitlines())
            lines.append("")

        # Guard: if no methods at all, add a pass
        if not sync_body and not comb_body:
            lines.append("    pass")

        result = "\n".join(lines) + "\n"
        ir.lowered_py["py/module/top"] = result
        _log.debug(
            "[ModuleAssemblePythonPass] assembled %d chars for %r",
            len(result),
            module_name,
        )
        return ir
