"""PipelineToSource — reconstruct annotated ``@zdc.pipeline`` Python from
:class:`~zuspec.synth.ir.pipeline_ir.PipelineIR`.

Used primarily after **Approach A** (SDC scheduling) to produce a human-readable,
copy-refinable Python method body so users can inspect the auto-scheduled stage
partition and, if desired, commit it as an Approach C annotation.

The output always uses Form 4 (named stages)::

    @zdc.pipeline(clock=lambda s: s.clk, reset=lambda s: s.rst,
                  stages=["IF", "EX", "WB"], forward=True)
    def execute(self):
        # Auto-generated by PipelineToSource — copy and refine as needed
        zdc.forward(from_stage="EX", to_stage="IF", signal="result")
        IF = zdc.stage()
        a: zdc.u32 = self.a
        EX = zdc.stage()
        result: zdc.u32 = a + self.b
        WB = zdc.stage()
        self.out = result

The pass stores the reconstructed source string in
``PipelineIR.source_annotation`` and also returns it.

Pass chain position
-------------------
This pass may be run immediately after :class:`SDCSchedulePass` to produce
Approach A output, or at the end of the full Approach C chain for
documentation purposes.
"""
from __future__ import annotations

import ast
import logging
import textwrap
from io import StringIO
from typing import List, Optional

from .synth_pass import SynthPass
from zuspec.synth.ir.pipeline_ir import ForwardingDecl, PipelineIR, StageIR
from zuspec.synth.ir.synth_ir import SynthConfig, SynthIR

_log = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _ast_to_source(stmt: ast.stmt) -> str:
    """Best-effort conversion of an AST statement back to Python source.

    Uses ``ast.unparse`` (Python ≥ 3.9) if available; falls back to a generic
    placeholder comment.
    """
    try:
        return ast.unparse(stmt)
    except AttributeError:
        return f"# <stmt: {type(stmt).__name__}>"


# ---------------------------------------------------------------------------
# PipelineToSource
# ---------------------------------------------------------------------------

class PipelineToSource:
    """Reconstruct an annotated ``@zdc.pipeline`` Python method body.

    This class is usable standalone (without a :class:`SynthIR` / pass chain)
    for testing or offline source generation.
    """

    def reconstruct(
        self,
        pip: PipelineIR,
        *,
        method_name: str = "execute",
        indent: str = "    ",
        add_decorator: bool = True,
    ) -> str:
        """Reconstruct the Python source for *pip*.

        Args:
            pip: The pipeline IR to reconstruct from.
            method_name: The method name in the output (default ``"execute"``).
            indent: Indentation string for the body (default 4 spaces).
            add_decorator: If ``True``, prepend the ``@zdc.pipeline(...)``
                decorator above the method signature.

        Returns:
            A Python source string that, when embedded in a class, reproduces
            an equivalent ``@zdc.pipeline`` method.
        """
        out = StringIO()

        if add_decorator:
            self._emit_decorator(out, pip)

        out.write(f"def {method_name}(self):\n")

        body_lines = self._reconstruct_body(pip, indent=indent)
        if not body_lines:
            out.write(f"{indent}pass\n")
        else:
            for line in body_lines:
                out.write(line + "\n")

        return out.getvalue()

    # ------------------------------------------------------------------
    # Decorator emission
    # ------------------------------------------------------------------

    def _emit_decorator(self, out: StringIO, pip: PipelineIR) -> None:
        """Emit the ``@zdc.pipeline(...)`` decorator line(s)."""
        stage_names = [s.name for s in pip.stages]
        stages_repr = repr(stage_names)

        forward_repr: str
        if pip.forward_default is True:
            forward_repr = "True"
        elif pip.forward_default is False:
            forward_repr = "False"
        else:
            forward_repr = "None"

        # Try to reconstruct clock/reset from module name (best-effort)
        out.write("@zdc.pipeline(\n")
        out.write("    clock=lambda s: s.clk,  # TODO: update clock signal\n")
        out.write("    reset=lambda s: s.rst,  # TODO: update reset signal\n")
        out.write(f"    stages={stages_repr},\n")
        out.write(f"    forward={forward_repr},\n")
        out.write(")\n")

    # ------------------------------------------------------------------
    # Body reconstruction
    # ------------------------------------------------------------------

    def _reconstruct_body(self, pip: PipelineIR, indent: str) -> List[str]:
        """Return a list of indented body lines (without trailing newlines)."""
        lines: List[str] = []

        # Header comment
        lines.append(f"{indent}# Auto-generated by PipelineToSource — "
                     f"copy and refine as needed")
        lines.append(f"{indent}# Pipeline: {pip.module_name}  "
                     f"approach={pip.approach}  II={pip.initiation_interval}")
        lines.append(f"{indent}#")

        # Forward / no_forward decls that differ from default
        forward_decls = self._select_explicit_decls(pip)
        for decl in forward_decls:
            fn = "forward" if not decl.suppressed else "no_forward"
            lines.append(
                f"{indent}zdc.{fn}("
                f'from_stage="{decl.from_stage}", '
                f'to_stage="{decl.to_stage}", '
                f'signal="{decl.signal}")'
            )

        if forward_decls:
            lines.append(f"{indent}")

        # Stages
        for stage in pip.stages:
            # Stage marker
            lines.append(f"{indent}{stage.name} = zdc.stage()")

            # Emit operations
            for stmt in stage.operations:
                src = _ast_to_source(stmt)
                for src_line in src.splitlines():
                    lines.append(f"{indent}{src_line}")

            lines.append(f"{indent}")  # blank line between stages

        return lines

    def _select_explicit_decls(
        self, pip: PipelineIR
    ) -> List[ForwardingDecl]:
        """Return forwarding decls that should be emitted explicitly in body.

        If ``forward_default`` covers all cases (all forwarding or all
        stalling), only decls that *override* the default are emitted.
        If ``forward_default`` is ``None``, all decls are emitted.
        """
        result = []
        for decl in pip.forwarding:
            if pip.forward_default is True and not decl.suppressed:
                # Default is forward; emitting a forward decl is redundant
                continue
            if pip.forward_default is False and decl.suppressed:
                # Default is stall; emitting a no_forward decl is redundant
                continue
            result.append(decl)
        return result


# ---------------------------------------------------------------------------
# SynthPass wrapper
# ---------------------------------------------------------------------------

class PipelineToSourcePass(SynthPass):
    """Synthesis pass wrapper for :class:`PipelineToSource`.

    Reconstructs the ``@zdc.pipeline`` Python source from
    ``ir.pipeline_ir`` and stores the result in
    ``ir.pipeline_ir.source_annotation``.

    This pass is a no-op when ``ir.pipeline_ir`` is ``None``.
    """

    def __init__(
        self,
        config: SynthConfig,
        *,
        method_name: str = "execute",
        indent: str = "    ",
    ) -> None:
        super().__init__(config=config)
        self._method_name = method_name
        self._indent = indent

    @property
    def name(self) -> str:
        return "pipeline_to_source"

    def run(self, ir: SynthIR) -> SynthIR:
        pip = getattr(ir, "pipeline_ir", None)
        if pip is None:
            _log.debug("[PipelineToSourcePass] no pipeline_ir — skipping")
            return ir

        source = PipelineToSource().reconstruct(
            pip,
            method_name=self._method_name,
            indent=self._indent,
        )
        pip.source_annotation = source
        _log.info(
            "[PipelineToSourcePass] reconstructed %d-stage pipeline '%s' (%d chars)",
            len(pip.stages),
            pip.module_name,
            len(source),
        )
        return ir
